"""
Authentication Request Module
FT-QuPAP Mobile Station

This module creates the initial pseudonymous authentication request
sent by the Mobile Station to the Authentication Server.

Notebook-aligned request structure:

    {
        "pseudonym_id": "PID-6G-UE-0001",
        "timestamp": <Unix timestamp>,
        "nonce": <Base64-encoded 16-byte nonce>,
        "service_context": "urban",
        "request_type": "FT-QuPAP-Authentication",
    }

Security properties:

1. Uses a pseudonym instead of a raw IMSI.
2. Generates a fresh cryptographic nonce for every attempt.
3. Includes a timestamp for server-side freshness checking.
4. Binds the request to a declared service context.
5. Creates a new nonce for every retry.

The Authentication Server is responsible for checking:

    - known pseudonym
    - subscriber status
    - timestamp freshness
    - nonce replay
    - permitted service context
"""

from __future__ import annotations

import base64
import hashlib
import json
import secrets
import time
from dataclasses import dataclass
from typing import Any, Mapping


REQUEST_TYPE = "FT-QuPAP-Authentication"
NONCE_LENGTH_BYTES = 16

SUPPORTED_CONTEXTS = (
    "urban",
    "suburban",
    "rural",
)

REQUIRED_REQUEST_FIELDS = frozenset(
    {
        "pseudonym_id",
        "timestamp",
        "nonce",
        "service_context",
        "request_type",
    }
)

FORBIDDEN_IDENTITY_FIELDS = frozenset(
    {
        "imsi",
        "raw_imsi",
        "subscriber_identity",
        "raw_subscriber_identity",
        "permanent_identity",
    }
)


class AuthenticationRequestError(Exception):
    """Raised when authentication-request processing fails."""


@dataclass(frozen=True)
class AuthenticationRequest:
    """
    Structured FT-QuPAP authentication request.

    Attributes:
        pseudonym_id:
            Operator-managed pseudonymous subscriber identifier.

        timestamp:
            Unix timestamp generated by the Mobile Station.

        nonce:
            Base64-encoded 16-byte session nonce.

        service_context:
            Declared network context.

        request_type:
            FT-QuPAP protocol request identifier.
    """

    pseudonym_id: str
    timestamp: int
    nonce: str
    service_context: str
    request_type: str = REQUEST_TYPE

    def __post_init__(self) -> None:
        validate_pseudonym_id(
            self.pseudonym_id
        )

        validate_timestamp(
            self.timestamp
        )

        validate_encoded_nonce(
            self.nonce
        )

        validate_service_context(
            self.service_context
        )

        if self.request_type != REQUEST_TYPE:
            raise ValueError(
                f"request_type must be {REQUEST_TYPE!r}."
            )

    def to_dictionary(self) -> dict[str, Any]:
        """Return the notebook-compatible request dictionary."""

        return {
            "pseudonym_id": self.pseudonym_id,
            "timestamp": self.timestamp,
            "nonce": self.nonce,
            "service_context": self.service_context,
            "request_type": self.request_type,
        }

    def to_bytes(self) -> bytes:
        """Serialize the request deterministically."""

        return canonical_json_bytes(
            self.to_dictionary()
        )

    @property
    def nonce_fingerprint(self) -> str:
        """
        Return a short nonce fingerprint for diagnostics.

        The complete nonce is not displayed.
        """

        return hashlib.sha3_256(
            decode_nonce(self.nonce)
        ).hexdigest()[:16]

    def safe_summary(self) -> dict[str, Any]:
        """Return request information without exposing the nonce."""

        return {
            "pseudonym_id": self.pseudonym_id,
            "timestamp": self.timestamp,
            "nonce_bytes": NONCE_LENGTH_BYTES,
            "nonce_fingerprint":
                self.nonce_fingerprint,
            "service_context":
                self.service_context,
            "request_type": self.request_type,
        }


def current_timestamp() -> int:
    """Return the current Unix timestamp."""

    return int(time.time())


def canonical_json_bytes(
    value: Mapping[str, Any],
) -> bytes:
    """
    Serialize a mapping into deterministic UTF-8 JSON.

    This format must remain consistent when the request is later
    included in H(Transcript).
    """

    if not isinstance(value, Mapping):
        raise TypeError(
            "value must be a mapping."
        )

    try:
        serialized = json.dumps(
            dict(value),
            sort_keys=True,
            separators=(",", ":"),
        )

    except (
        TypeError,
        ValueError,
    ) as error:
        raise AuthenticationRequestError(
            "Unable to serialize authentication request."
        ) from error

    return serialized.encode("utf-8")


def encode_base64(data: bytes) -> str:
    """Encode bytes as Base64 ASCII text."""

    if not isinstance(data, bytes):
        raise TypeError(
            "data must be bytes."
        )

    if not data:
        raise ValueError(
            "data cannot be empty."
        )

    return base64.b64encode(
        data
    ).decode("ascii")


def decode_base64(
    encoded_value: str,
    field_name: str = "encoded_value",
) -> bytes:
    """Decode strict Base64 ASCII text."""

    if not isinstance(encoded_value, str):
        raise TypeError(
            f"{field_name} must be a string."
        )

    if not encoded_value:
        raise ValueError(
            f"{field_name} cannot be empty."
        )

    try:
        return base64.b64decode(
            encoded_value.encode("ascii"),
            validate=True,
        )

    except Exception as error:
        raise ValueError(
            f"{field_name} is not valid Base64."
        ) from error


def generate_nonce(
    length: int = NONCE_LENGTH_BYTES,
) -> bytes:
    """
    Generate a cryptographically secure nonce.

    Standard FT-QuPAP uses a fresh 16-byte nonce.
    """

    if isinstance(length, bool):
        raise TypeError(
            "length must be an integer."
        )

    if not isinstance(length, int):
        raise TypeError(
            "length must be an integer."
        )

    if length != NONCE_LENGTH_BYTES:
        raise ValueError(
            "FT-QuPAP authentication nonces must contain "
            f"exactly {NONCE_LENGTH_BYTES} bytes."
        )

    return secrets.token_bytes(length)


def validate_pseudonym_id(
    pseudonym_id: str,
) -> None:
    """
    Validate the pseudonymous subscriber identifier.
    """

    if not isinstance(pseudonym_id, str):
        raise TypeError(
            "pseudonym_id must be a string."
        )

    if not pseudonym_id.strip():
        raise ValueError(
            "pseudonym_id cannot be empty."
        )

    if len(pseudonym_id) > 128:
        raise ValueError(
            "pseudonym_id is too long."
        )

    if not pseudonym_id.startswith("PID-"):
        raise ValueError(
            "pseudonym_id must begin with 'PID-'."
        )


def validate_timestamp(
    timestamp: int,
) -> None:
    """Validate a Unix timestamp."""

    if isinstance(timestamp, bool):
        raise TypeError(
            "timestamp must be an integer."
        )

    if not isinstance(timestamp, int):
        raise TypeError(
            "timestamp must be an integer."
        )

    if timestamp < 0:
        raise ValueError(
            "timestamp cannot be negative."
        )


def validate_service_context(
    context: str,
) -> None:
    """Validate the declared service context."""

    if not isinstance(context, str):
        raise TypeError(
            "context must be a string."
        )

    if context not in SUPPORTED_CONTEXTS:
        raise ValueError(
            "Unsupported service context. "
            f"Expected one of {SUPPORTED_CONTEXTS}."
        )


def validate_raw_nonce(
    nonce: bytes,
) -> None:
    """Validate a raw FT-QuPAP nonce."""

    if not isinstance(nonce, bytes):
        raise TypeError(
            "nonce must be bytes."
        )

    if len(nonce) != NONCE_LENGTH_BYTES:
        raise ValueError(
            "FT-QuPAP nonce must contain exactly "
            f"{NONCE_LENGTH_BYTES} bytes."
        )


def validate_encoded_nonce(
    encoded_nonce: str,
) -> None:
    """Validate a Base64-encoded FT-QuPAP nonce."""

    decoded_nonce = decode_base64(
        encoded_nonce,
        "nonce",
    )

    validate_raw_nonce(
        decoded_nonce
    )


def decode_nonce(
    encoded_nonce: str,
) -> bytes:
    """Decode and validate an authentication nonce."""

    decoded_nonce = decode_base64(
        encoded_nonce,
        "nonce",
    )

    validate_raw_nonce(
        decoded_nonce
    )

    return decoded_nonce


def create_authentication_request_object(
    pseudonym_id: str,
    context: str = "urban",
    timestamp: int | None = None,
    nonce: bytes | None = None,
) -> AuthenticationRequest:
    """
    Create a structured FT-QuPAP authentication request.

    Args:
        pseudonym_id:
            Registered pseudonymous subscriber identifier.

        context:
            Service context: urban, suburban, or rural.

        timestamp:
            Optional Unix timestamp for deterministic testing.
            Current time is used when omitted.

        nonce:
            Optional 16-byte nonce for deterministic testing.
            A secure random nonce is generated when omitted.

    Returns:
        AuthenticationRequest object.
    """

    validate_pseudonym_id(
        pseudonym_id
    )

    validate_service_context(
        context
    )

    if timestamp is None:
        request_timestamp = (
            current_timestamp()
        )
    else:
        if isinstance(timestamp, bool):
            raise TypeError(
                "timestamp must be an integer."
            )

        try:
            request_timestamp = int(
                timestamp
            )

        except (
            TypeError,
            ValueError,
            OverflowError,
        ) as error:
            raise ValueError(
                "timestamp cannot be converted to an integer."
            ) from error

    validate_timestamp(
        request_timestamp
    )

    if nonce is None:
        request_nonce = generate_nonce()
    else:
        validate_raw_nonce(nonce)
        request_nonce = bytes(nonce)

    return AuthenticationRequest(
        pseudonym_id=pseudonym_id.strip(),
        timestamp=request_timestamp,
        nonce=encode_base64(
            request_nonce
        ),
        service_context=context,
        request_type=REQUEST_TYPE,
    )


def create_authentication_request(
    pseudonym_id: str,
    context: str = "urban",
    timestamp: int | None = None,
    nonce: bytes | None = None,
) -> dict[str, Any]:
    """
    Create the notebook-compatible Mobile Station request.

    This is the primary function imported by mobile_station.py.

    Returns:
        Dictionary containing exactly:

        - pseudonym_id
        - timestamp
        - nonce
        - service_context
        - request_type
    """

    request = (
        create_authentication_request_object(
            pseudonym_id=pseudonym_id,
            context=context,
            timestamp=timestamp,
            nonce=nonce,
        )
    )

    return request.to_dictionary()


def validate_authentication_request(
    request: Mapping[str, Any],
    reject_extra_fields: bool = True,
) -> None:
    """
    Validate the structure of an authentication request.

    This performs format validation only.

    It does not validate:

        - timestamp freshness
        - nonce replay
        - subscriber registration
        - subscriber status

    Those checks belong to the Authentication Server.
    """

    if not isinstance(request, Mapping):
        raise TypeError(
            "request must be a mapping."
        )

    request_keys = set(
        request.keys()
    )

    forbidden_fields = (
        request_keys
        & FORBIDDEN_IDENTITY_FIELDS
    )

    if forbidden_fields:
        raise AuthenticationRequestError(
            "Authentication request contains forbidden "
            "permanent identity fields: "
            f"{sorted(forbidden_fields)}"
        )

    missing_fields = (
        REQUIRED_REQUEST_FIELDS
        .difference(request_keys)
    )

    if missing_fields:
        raise AuthenticationRequestError(
            "Authentication request is missing fields: "
            f"{sorted(missing_fields)}"
        )

    if reject_extra_fields:
        extra_fields = (
            request_keys
            .difference(
                REQUIRED_REQUEST_FIELDS
            )
        )

        if extra_fields:
            raise AuthenticationRequestError(
                "Authentication request contains unexpected "
                f"fields: {sorted(extra_fields)}"
            )

    validate_pseudonym_id(
        request["pseudonym_id"]
    )

    validate_timestamp(
        request["timestamp"]
    )

    validate_encoded_nonce(
        request["nonce"]
    )

    validate_service_context(
        request["service_context"]
    )

    if request["request_type"] != REQUEST_TYPE:
        raise AuthenticationRequestError(
            f"request_type must be {REQUEST_TYPE!r}."
        )


def request_from_dictionary(
    request: Mapping[str, Any],
) -> AuthenticationRequest:
    """Convert a validated dictionary into an object."""

    validate_authentication_request(
        request
    )

    return AuthenticationRequest(
        pseudonym_id=
            request["pseudonym_id"],
        timestamp=
            request["timestamp"],
        nonce=
            request["nonce"],
        service_context=
            request["service_context"],
        request_type=
            request["request_type"],
    )


def requests_use_different_nonces(
    first_request: Mapping[str, Any],
    second_request: Mapping[str, Any],
) -> bool:
    """
    Check that two attempts use different nonces.

    A retry must always create a fresh request and session.
    """

    validate_authentication_request(
        first_request
    )

    validate_authentication_request(
        second_request
    )

    return (
        first_request["nonce"]
        != second_request["nonce"]
    )


def safe_request_summary(
    request: Mapping[str, Any],
) -> dict[str, Any]:
    """Return a summary without exposing the complete nonce."""

    request_object = request_from_dictionary(
        request
    )

    return request_object.safe_summary()


def run_self_test() -> None:
    """
    Test request creation, validation, nonce encoding,
    pseudonym use, and retry freshness.
    """

    print("=" * 70)
    print("FT-QuPAP Authentication Request Self-Test")
    print("=" * 70)

    fixed_nonce = (
        b"0123456789ABCDEF"
    )

    fixed_timestamp = 1785520000

    fixed_request = (
        create_authentication_request(
            pseudonym_id=
                "PID-6G-UE-0001",
            context="urban",
            timestamp=fixed_timestamp,
            nonce=fixed_nonce,
        )
    )

    validate_authentication_request(
        fixed_request
    )

    recovered_nonce = decode_nonce(
        fixed_request["nonce"]
    )

    nonce_round_trip_valid = (
        recovered_nonce == fixed_nonce
    )

    first_fresh_request = (
        create_authentication_request(
            pseudonym_id=
                "PID-6G-UE-0001",
            context="urban",
        )
    )

    second_fresh_request = (
        create_authentication_request(
            pseudonym_id=
                "PID-6G-UE-0001",
            context="urban",
        )
    )

    fresh_nonces_different = (
        requests_use_different_nonces(
            first_fresh_request,
            second_fresh_request,
        )
    )

    exact_fields_valid = (
        set(fixed_request.keys())
        == REQUIRED_REQUEST_FIELDS
    )

    raw_identity_absent = all(
        field not in fixed_request
        for field
        in FORBIDDEN_IDENTITY_FIELDS
    )

    unsupported_context_rejected = False

    try:
        create_authentication_request(
            pseudonym_id=
                "PID-6G-UE-0001",
            context="satellite",
        )

    except ValueError:
        unsupported_context_rejected = True

    print(
        f"Pseudonym ID             : "
        f"{fixed_request['pseudonym_id']}"
    )
    print(
        f"Timestamp                : "
        f"{fixed_request['timestamp']}"
    )
    print(
        f"Nonce bytes              : "
        f"{len(recovered_nonce)}"
    )
    print(
        f"Service context          : "
        f"{fixed_request['service_context']}"
    )
    print(
        f"Request type             : "
        f"{fixed_request['request_type']}"
    )
    print(
        f"Exact request fields     : "
        f"{exact_fields_valid}"
    )
    print(
        f"Nonce round-trip valid   : "
        f"{nonce_round_trip_valid}"
    )
    print(
        f"Fresh nonces differ      : "
        f"{fresh_nonces_different}"
    )
    print(
        f"Raw identity absent      : "
        f"{raw_identity_absent}"
    )
    print(
        f"Bad context rejected     : "
        f"{unsupported_context_rejected}"
    )

    if not exact_fields_valid:
        raise AuthenticationRequestError(
            "Request contains incorrect fields."
        )

    if not nonce_round_trip_valid:
        raise AuthenticationRequestError(
            "Nonce Base64 round-trip failed."
        )

    if not fresh_nonces_different:
        raise AuthenticationRequestError(
            "Two fresh requests reused the same nonce."
        )

    if not raw_identity_absent:
        raise AuthenticationRequestError(
            "Request exposed a permanent subscriber identity."
        )

    if not unsupported_context_rejected:
        raise AuthenticationRequestError(
            "Unsupported service context was accepted."
        )

    print("\nSafe request summary:")

    print(
        json.dumps(
            safe_request_summary(
                fixed_request
            ),
            indent=4,
        )
    )

    print(
        "\nAuthentication request self-test "
        "completed successfully."
    )


__all__ = [
    "AuthenticationRequest",
    "AuthenticationRequestError",
    "REQUEST_TYPE",
    "NONCE_LENGTH_BYTES",
    "SUPPORTED_CONTEXTS",
    "current_timestamp",
    "generate_nonce",
    "create_authentication_request_object",
    "create_authentication_request",
    "validate_authentication_request",
    "decode_nonce",
    "safe_request_summary",
]


if __name__ == "__main__":
    try:
        run_self_test()

    except (
        AuthenticationRequestError,
        TypeError,
        ValueError,
    ) as error:
        print(
            "\n[AUTHENTICATION REQUEST ERROR] "
            f"{error}"
        )