"""
Research-results page for the FT-QuPAP Streamlit dashboard.

The page presents only stored and traceable evidence generated by the
FT-QuPAP notebook or approved project scripts. It organizes results into the
same categories required by the protocol-and-results storage report:

- correctness and valid-user availability
- security detection and false acceptance
- Gaussian Process discrimination and calibration
- quantum-channel and Steane CSS behavior
- retry-policy outcomes
- baseline comparison
- protocol runtime and resource cost
- representative Qiskit/Aer validation
- reproducibility metadata and artifact inventory

No numerical result is embedded as a fallback. A metric appears only when a
managed CSV/JSON artifact contains that value. Missing evidence is rendered
as unavailable.

Research boundary
-----------------
Full protocol sessions are syndrome-level simulations. Qiskit/Aer results are
representative encoded-block validation. GP output is a calibrated attack
probability under the evaluated data distribution, not proof of
eavesdropping. Development/demo evidence is labeled and must not be silently
presented as final paper evidence.

Security boundary
-----------------
Result tables are passed through the dashboard redaction layer. Private keys,
shared secrets, K_auth, K_ctrl, K_ss, raw subscriber identities, ciphertexts,
signatures, and raw authentication tags are never displayed or exported.
"""

from __future__ import annotations

import csv
import json
import math
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Final, Iterable, Mapping, Sequence

from .charts import (
    ChartDataError,
    add_evidence_annotation,
    build_attack_probability_comparison,
    build_calibration_curve,
    build_confusion_matrix,
    build_precision_recall_curve,
    build_qber_comparison,
    build_retry_analysis,
    build_roc_curve,
    chart_source_status,
    first_existing_column,
    infer_evidence_scope,
    render_plotly_figure,
    render_saved_figure_gallery,
)
from .components import (
    KeyValueItem,
    MetricItem,
    format_bytes,
    format_duration,
    format_percentage,
    format_probability,
    format_value,
    render_banner,
    render_empty_state,
    render_json_download,
    render_json_viewer,
    render_key_value_grid,
    render_metric_grid,
    render_records_table,
    render_sensitive_data_notice,
    sanitize_mapping,
)
from .theme import (
    apply_dashboard_theme,
    render_divider,
    render_page_header,
    render_research_notice,
    render_section_title,
)


PROJECT_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
DATA_DIR: Final[Path] = PROJECT_ROOT / "data"
RESULTS_DIR: Final[Path] = DATA_DIR / "results"
PROCESSED_DIR: Final[Path] = DATA_DIR / "processed"
DEMO_DIR: Final[Path] = DATA_DIR / "demo"
MODELS_DIR: Final[Path] = PROJECT_ROOT / "models"
OUTPUTS_DIR: Final[Path] = PROJECT_ROOT / "outputs"
FIGURES_DIR: Final[Path] = OUTPUTS_DIR / "figures"
REPORTS_DIR: Final[Path] = OUTPUTS_DIR / "reports"

PERFORMANCE_METRICS_FILE: Final[Path] = (
    RESULTS_DIR / "performance_metrics.csv"
)
CONFUSION_MATRIX_FILE: Final[Path] = (
    RESULTS_DIR / "confusion_matrix.csv"
)
CALIBRATION_RESULTS_FILE: Final[Path] = (
    RESULTS_DIR / "calibration_results.csv"
)
THRESHOLD_ANALYSIS_FILE: Final[Path] = (
    RESULTS_DIR / "threshold_analysis.csv"
)
BASELINE_COMPARISON_FILE: Final[Path] = (
    RESULTS_DIR / "baseline_comparison.csv"
)
RETRY_RESULTS_FILE: Final[Path] = RESULTS_DIR / "retry_results.csv"
EXPERIMENT_RESULTS_FILE: Final[Path] = (
    RESULTS_DIR / "experiment_results.csv"
)
PAPER_CONFIDENCE_INTERVALS_FILE: Final[Path] = (
    RESULTS_DIR / "paper_confidence_intervals.csv"
)
QBER_STATISTICS_FILE: Final[Path] = (
    RESULTS_DIR / "qber_statistics.csv"
)
LOGICAL_BLOCK_STATISTICS_FILE: Final[Path] = (
    RESULTS_DIR / "logical_block_statistics.csv"
)
RUNTIME_STATISTICS_FILE: Final[Path] = (
    RESULTS_DIR / "runtime_statistics.csv"
)
QISKIT_VALIDATION_FILE: Final[Path] = (
    RESULTS_DIR / "qiskit_validation_results.csv"
)
INDEPENDENT_RESULTS_FILE: Final[Path] = (
    RESULTS_DIR / "independent_seed_results.csv"
)
SCENARIO_SUMMARY_FILE: Final[Path] = (
    RESULTS_DIR / "scenario_summary.csv"
)
REJECTION_REASONS_FILE: Final[Path] = (
    RESULTS_DIR / "rejection_reason_distribution.csv"
)

HELD_OUT_PREDICTIONS_FILE: Final[Path] = (
    RESULTS_DIR / "held_out_predictions.csv"
)
INDEPENDENT_PREDICTIONS_FILE: Final[Path] = (
    RESULTS_DIR / "independent_predictions.csv"
)
INDEPENDENT_TEST_FEATURES_FILE: Final[Path] = (
    PROCESSED_DIR / "independent_test_features.csv"
)
DASHBOARD_RESULTS_FILE: Final[Path] = (
    DEMO_DIR / "dashboard_results.csv"
)
DEMO_SESSION_LOGS_FILE: Final[Path] = (
    DEMO_DIR / "demo_session_logs.csv"
)

MODEL_METADATA_FILE: Final[Path] = (
    MODELS_DIR / "model_metadata.json"
)
THRESHOLD_FILE: Final[Path] = MODELS_DIR / "threshold.json"
FEATURE_ORDER_FILE: Final[Path] = (
    MODELS_DIR / "feature_order.json"
)

RUN_METADATA_CANDIDATES: Final[tuple[Path, ...]] = (
    RESULTS_DIR / "run_metadata.json",
    OUTPUTS_DIR / "run_metadata.json",
    MODELS_DIR / "model_metadata.json",
)

RESULT_TABLES: Final[dict[str, Path]] = {
    "Performance metrics": PERFORMANCE_METRICS_FILE,
    "Confusion matrix": CONFUSION_MATRIX_FILE,
    "Calibration results": CALIBRATION_RESULTS_FILE,
    "Threshold analysis": THRESHOLD_ANALYSIS_FILE,
    "Baseline comparison": BASELINE_COMPARISON_FILE,
    "Retry results": RETRY_RESULTS_FILE,
    "Experiment results": EXPERIMENT_RESULTS_FILE,
    "Paper confidence intervals": PAPER_CONFIDENCE_INTERVALS_FILE,
    "QBER statistics": QBER_STATISTICS_FILE,
    "Logical-block statistics": LOGICAL_BLOCK_STATISTICS_FILE,
    "Runtime statistics": RUNTIME_STATISTICS_FILE,
    "Qiskit validation": QISKIT_VALIDATION_FILE,
    "Independent-seed results": INDEPENDENT_RESULTS_FILE,
    "Scenario summary": SCENARIO_SUMMARY_FILE,
    "Rejection reasons": REJECTION_REASONS_FILE,
}

PREDICTION_SOURCES: Final[tuple[Path, ...]] = (
    INDEPENDENT_PREDICTIONS_FILE,
    HELD_OUT_PREDICTIONS_FILE,
    INDEPENDENT_TEST_FEATURES_FILE,
    EXPERIMENT_RESULTS_FILE,
    DASHBOARD_RESULTS_FILE,
    DEMO_SESSION_LOGS_FILE,
)

LABEL_COLUMNS: Final[tuple[str, ...]] = (
    "label_attack",
    "actual_attack",
    "is_attack",
    "attack_label",
)
PROBABILITY_COLUMNS: Final[tuple[str, ...]] = (
    "p_attack",
    "attack_probability",
    "calibrated_attack_probability",
    "calibrated_probability",
)
EVIDENCE_SCOPE_COLUMNS: Final[tuple[str, ...]] = (
    "evidence_scope",
    "research_scope",
    "data_origin",
)

METRIC_ALIASES: Final[dict[str, tuple[str, ...]]] = {
    "held_out_roc_auc": (
        "held_out_roc_auc",
        "test_roc_auc",
        "roc_auc",
    ),
    "held_out_pr_auc": (
        "held_out_pr_auc",
        "test_pr_auc",
        "pr_auc",
        "average_precision",
    ),
    "held_out_brier_score": (
        "held_out_brier_score",
        "test_brier_score",
        "brier_score",
        "brier",
    ),
    "held_out_ece": (
        "held_out_ece",
        "expected_calibration_error",
        "ece",
    ),
    "independent_roc_auc": (
        "independent_roc_auc",
        "independent_test_roc_auc",
    ),
    "independent_pr_auc": (
        "independent_pr_auc",
        "independent_test_pr_auc",
        "independent_average_precision",
    ),
    "operational_threshold": (
        "operational_threshold",
        "gp_attack_threshold",
        "selected_threshold",
        "threshold",
    ),
    "attack_detection_rate": (
        "attack_detection_rate",
        "attack_detection",
        "true_positive_rate",
        "recall_attack",
    ),
    "attack_acceptance_rate": (
        "attack_acceptance_rate",
        "false_accept_rate",
        "attack_acceptance",
    ),
    "valid_user_acceptance_rate": (
        "valid_user_acceptance_rate",
        "benign_acceptance_rate",
        "valid_acceptance_rate",
    ),
    "false_reject_rate": (
        "false_reject_rate",
        "benign_rejection_rate",
        "valid_user_rejection_rate",
    ),
    "tag_recovery_success_rate": (
        "tag_recovery_success_rate",
        "tag_recovery_rate",
        "logical_tag_success_rate",
    ),
    "retry_success_rate": (
        "retry_success_rate",
        "accepted_after_retry_rate",
    ),
    "end_to_end_seconds": (
        "end_to_end_seconds",
        "end_to_end_s",
        "mean_end_to_end_seconds",
        "mean_end_to_end_s",
    ),
    "physical_qubits": (
        "physical_qubits",
        "total_physical_qubits",
    ),
}

METRIC_PRESENTATION: Final[dict[str, tuple[str, str, str]]] = {
    "held_out_roc_auc": (
        "Held-out ROC-AUC",
        "probability",
        "Discrimination on the held-out test split",
    ),
    "held_out_pr_auc": (
        "Held-out PR-AUC",
        "probability",
        "Precision–recall quality on held-out sessions",
    ),
    "held_out_brier_score": (
        "Held-out Brier score",
        "probability",
        "Lower is better for probability accuracy",
    ),
    "held_out_ece": (
        "Held-out ECE",
        "probability",
        "Expected calibration error",
    ),
    "independent_roc_auc": (
        "Independent ROC-AUC",
        "probability",
        "Discrimination on independent evaluation seeds",
    ),
    "independent_pr_auc": (
        "Independent PR-AUC",
        "probability",
        "Precision–recall quality on independent seeds",
    ),
    "operational_threshold": (
        "Operational threshold",
        "probability",
        "Threshold selected without test-set tuning",
    ),
    "attack_detection_rate": (
        "Attack detection",
        "percentage",
        "Fraction of attack sessions rejected/detected",
    ),
    "attack_acceptance_rate": (
        "Attack acceptance",
        "percentage",
        "Accepted attack-session fraction",
    ),
    "valid_user_acceptance_rate": (
        "Valid-user acceptance",
        "percentage",
        "Accepted legitimate-session fraction",
    ),
    "false_reject_rate": (
        "False rejection",
        "percentage",
        "Rejected legitimate-session fraction",
    ),
    "tag_recovery_success_rate": (
        "Tag recovery",
        "percentage",
        "Successfully recovered authentication tags",
    ),
    "retry_success_rate": (
        "Retry success",
        "percentage",
        "Sessions successfully recovered through fresh retry",
    ),
    "end_to_end_seconds": (
        "End-to-end time",
        "duration",
        "Mean protocol session execution time",
    ),
    "physical_qubits": (
        "Physical data qubits",
        "integer",
        "Full logical-frame Steane expansion",
    ),
}

CATEGORY_REQUIREMENTS: Final[dict[str, tuple[Path, ...]]] = {
    "Correctness": (
        PAPER_CONFIDENCE_INTERVALS_FILE,
        EXPERIMENT_RESULTS_FILE,
        LOGICAL_BLOCK_STATISTICS_FILE,
    ),
    "Security detection": (
        EXPERIMENT_RESULTS_FILE,
        REJECTION_REASONS_FILE,
        PAPER_CONFIDENCE_INTERVALS_FILE,
    ),
    "GP quality": (
        PERFORMANCE_METRICS_FILE,
        CALIBRATION_RESULTS_FILE,
        THRESHOLD_ANALYSIS_FILE,
        CONFUSION_MATRIX_FILE,
    ),
    "Quantum channel": (
        QBER_STATISTICS_FILE,
        LOGICAL_BLOCK_STATISTICS_FILE,
    ),
    "Retry policy": (
        RETRY_RESULTS_FILE,
        EXPERIMENT_RESULTS_FILE,
    ),
    "Baseline comparison": (
        BASELINE_COMPARISON_FILE,
    ),
    "Protocol cost": (
        RUNTIME_STATISTICS_FILE,
    ),
    "Qiskit validation": (
        QISKIT_VALIDATION_FILE,
    ),
    "Reproducibility": (
        MODEL_METADATA_FILE,
        THRESHOLD_FILE,
        FEATURE_ORDER_FILE,
    ),
}


class ResultsViewError(ValueError):
    """Raised when stored result evidence cannot be interpreted safely."""


@dataclass(frozen=True)
class ArtifactStatus:
    """Availability and provenance details for one managed artifact."""

    name: str
    path: str
    exists: bool
    bytes: int
    modified_at_utc: str | None
    row_count: int | None
    evidence_scope: str

    def to_dictionary(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class PredictionEvidence:
    """A prediction table suitable for ROC/PR/calibration charts."""

    source: str
    row_count: int
    label_column: str
    probability_column: str
    evidence_scope: str
    rows: tuple[Mapping[str, Any], ...]


@dataclass(frozen=True)
class ResultsSnapshot:
    """Pure state used to render the results page."""

    generated_at_utc: str
    evidence_scope: str
    model_id: str | None
    protocol_version: str | None
    master_seed: int | None
    metric_values: Mapping[str, Any]
    threshold_values: Mapping[str, Any]
    model_metadata: Mapping[str, Any]
    run_metadata: Mapping[str, Any]
    artifacts: tuple[ArtifactStatus, ...]
    prediction_evidence: PredictionEvidence | None
    available_categories: Mapping[str, bool]
    warnings: tuple[str, ...] = field(default_factory=tuple)

    def to_dictionary(self) -> dict[str, Any]:
        return sanitize_mapping(asdict(self))


def _streamlit() -> Any:
    """Import Streamlit only when rendering is required."""

    try:
        import streamlit as st  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "Streamlit is required to render dashboard/results_view.py."
        ) from exc

    return st


def _pandas() -> Any:
    """Import pandas lazily."""

    try:
        import pandas as pd  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "pandas is required for result-table exploration."
        ) from exc

    return pd


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _finite_float(value: Any) -> float | None:
    if value is None or isinstance(value, bool):
        return None

    try:
        number = float(value)
    except (TypeError, ValueError):
        return None

    return number if math.isfinite(number) else None


def _optional_int(value: Any) -> int | None:
    if value is None or isinstance(value, bool):
        return None

    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _coerce_scalar(value: Any) -> Any:
    """Convert CSV strings into safe scalar values."""

    if value is None or isinstance(value, (bool, int, float)):
        return value

    text = str(value).strip()

    if not text:
        return None

    normalized = text.lower()

    if normalized in {"true", "yes", "y"}:
        return True

    if normalized in {"false", "no", "n"}:
        return False

    if normalized in {"none", "null", "nan", "n/a"}:
        return None

    try:
        integer = int(text)

        if text == str(integer):
            return integer
    except ValueError:
        pass

    try:
        number = float(text)

        if math.isfinite(number):
            return number
    except ValueError:
        pass

    if (
        (text.startswith("{") and text.endswith("}"))
        or (text.startswith("[") and text.endswith("]"))
    ):
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

    return text


def _safe_read_json(path: Path) -> Any:
    if not path.is_file():
        return None

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return None


def _safe_read_csv_rows(
    path: Path,
    *,
    maximum_rows: int | None = None,
) -> list[dict[str, Any]]:
    """Read and redact a CSV table without requiring pandas."""

    if not path.is_file():
        return []

    rows: list[dict[str, Any]] = []

    try:
        with path.open(
            "r",
            encoding="utf-8-sig",
            newline="",
        ) as stream:
            reader = csv.DictReader(stream)

            if reader.fieldnames is None:
                return []

            for raw in reader:
                normalized = {
                    str(key): _coerce_scalar(value)
                    for key, value in raw.items()
                }
                safe = sanitize_mapping(normalized)

                if isinstance(safe, Mapping):
                    rows.append(dict(safe))

                if (
                    maximum_rows is not None
                    and len(rows) >= maximum_rows
                ):
                    break
    except (OSError, UnicodeError, csv.Error):
        return []

    return rows


def _normalize_name(value: Any) -> str:
    return (
        str(value)
        .strip()
        .lower()
        .replace("%", "percent")
        .replace("-", "_")
        .replace(" ", "_")
        .replace("(", "")
        .replace(")", "")
        .replace("/", "_")
    )


def _metric_mapping_from_rows(
    rows: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Support both long metric/value and wide one-row CSV formats."""

    if not rows:
        return {}

    columns = set(rows[0])
    metric_column = next(
        (
            name
            for name in (
                "metric",
                "metric_name",
                "name",
                "measure",
            )
            if name in columns
        ),
        None,
    )
    value_column = next(
        (
            name
            for name in (
                "value",
                "metric_value",
                "score",
                "result",
                "mean",
            )
            if name in columns
        ),
        None,
    )

    if metric_column is not None and value_column is not None:
        return {
            _normalize_name(row.get(metric_column)): row.get(value_column)
            for row in rows
            if row.get(metric_column) is not None
        }

    if len(rows) == 1:
        return {
            _normalize_name(key): value
            for key, value in rows[0].items()
            if value is not None
        }

    # Multi-row wide files can have split/evaluation labels.
    mapping: dict[str, Any] = {}

    for row in rows:
        prefix_value = next(
            (
                row.get(name)
                for name in (
                    "split",
                    "evaluation",
                    "dataset",
                    "scope",
                    "source",
                )
                if row.get(name) is not None
            ),
            None,
        )
        prefix = (
            _normalize_name(prefix_value)
            if prefix_value is not None
            else ""
        )

        for key, value in row.items():
            if value is None:
                continue

            normalized_key = _normalize_name(key)

            if normalized_key in {
                "split",
                "evaluation",
                "dataset",
                "scope",
                "source",
            }:
                continue

            combined = (
                f"{prefix}_{normalized_key}"
                if prefix
                else normalized_key
            )
            mapping[combined] = value
            mapping.setdefault(normalized_key, value)

    return mapping


def _lookup_alias(
    mapping: Mapping[str, Any],
    aliases: Sequence[str],
) -> Any:
    normalized_mapping = {
        _normalize_name(key): value
        for key, value in mapping.items()
    }

    for alias in aliases:
        normalized = _normalize_name(alias)

        if normalized in normalized_mapping:
            return normalized_mapping[normalized]

    return None


def load_metric_values() -> dict[str, Any]:
    """Load canonical metrics from managed result tables."""

    combined: dict[str, Any] = {}

    for path in (
        PERFORMANCE_METRICS_FILE,
        PAPER_CONFIDENCE_INTERVALS_FILE,
        EXPERIMENT_RESULTS_FILE,
        RUNTIME_STATISTICS_FILE,
        BASELINE_COMPARISON_FILE,
    ):
        mapping = _metric_mapping_from_rows(
            _safe_read_csv_rows(path)
        )

        for key, value in mapping.items():
            combined.setdefault(key, value)

    threshold_payload = _safe_read_json(THRESHOLD_FILE)

    if isinstance(threshold_payload, Mapping):
        for key, value in threshold_payload.items():
            combined.setdefault(_normalize_name(key), value)

    canonical: dict[str, Any] = {}

    for name, aliases in METRIC_ALIASES.items():
        value = _lookup_alias(combined, aliases)

        if value is not None:
            canonical[name] = value

    return canonical


def load_threshold_values() -> dict[str, Any]:
    """Load non-secret deployed policy values."""

    payload = _safe_read_json(THRESHOLD_FILE)

    if not isinstance(payload, Mapping):
        return {}

    allowed = {
        "operational_threshold",
        "minimum_operational_threshold",
        "gp_attack_threshold",
        "retry_upper_probability",
        "gp_gray_zone_retry_upper",
        "fixed_qber_threshold",
        "maximum_loss_rate",
        "max_acceptable_loss_rate",
        "minimum_observed_check_blocks",
        "min_observed_check_blocks",
        "maximum_authentication_attempts",
        "max_authentication_attempts",
        "false_accept_cost",
        "false_reject_cost",
        "selected_on",
        "calibration_split",
        "threshold_policy_version",
    }

    safe = sanitize_mapping(
        {
            str(key): value
            for key, value in payload.items()
            if str(key) in allowed
        }
    )

    return dict(safe) if isinstance(safe, Mapping) else {}


def load_model_metadata() -> dict[str, Any]:
    """Load approved non-secret model provenance fields."""

    payload = _safe_read_json(MODEL_METADATA_FILE)

    if not isinstance(payload, Mapping):
        return {}

    blocked_fragments = (
        "private",
        "secret",
        "ciphertext",
        "raw_tag",
        "authentication_tag",
        "subscriber",
        "imsi",
    )

    filtered = {
        str(key): value
        for key, value in payload.items()
        if not any(
            fragment in str(key).lower()
            for fragment in blocked_fragments
        )
    }
    safe = sanitize_mapping(filtered)

    return dict(safe) if isinstance(safe, Mapping) else {}


def load_run_metadata() -> dict[str, Any]:
    """Load the first available run metadata record."""

    for path in RUN_METADATA_CANDIDATES:
        payload = _safe_read_json(path)

        if isinstance(payload, Mapping):
            safe = sanitize_mapping(payload)

            if isinstance(safe, Mapping):
                result = dict(safe)
                result["_source_file"] = str(
                    path.relative_to(PROJECT_ROOT)
                )
                return result

    return {}


def _artifact_modified_iso(path: Path) -> str | None:
    if not path.is_file():
        return None

    return datetime.fromtimestamp(
        path.stat().st_mtime,
        tz=timezone.utc,
    ).isoformat(timespec="seconds")


def _artifact_row_count(path: Path) -> int | None:
    if path.suffix.lower() != ".csv" or not path.is_file():
        return None

    # Count line records without loading the full file into memory.
    try:
        with path.open(
            "r",
            encoding="utf-8-sig",
            newline="",
        ) as stream:
            reader = csv.reader(stream)
            count = sum(1 for _ in reader)
        return max(0, count - 1)
    except (OSError, UnicodeError, csv.Error):
        return None


def _artifact_scope(path: Path) -> str:
    """Infer conservative evidence scope from content or directory."""

    if path.suffix.lower() == ".json":
        payload = _safe_read_json(path)

        if isinstance(payload, Mapping):
            for key in (
                "evidence_scope",
                "research_scope",
                "source_research_scope",
                "data_origin",
            ):
                if payload.get(key) is not None:
                    return str(payload[key])

    if path.suffix.lower() == ".csv":
        rows = _safe_read_csv_rows(path, maximum_rows=50)

        for column in EVIDENCE_SCOPE_COLUMNS:
            values = {
                str(row[column])
                for row in rows
                if row.get(column) is not None
            }

            if len(values) == 1:
                return next(iter(values))

            if len(values) > 1:
                return "mixed"

    if DEMO_DIR in path.parents:
        return "development_or_demo"

    return "unspecified"


def build_artifact_inventory() -> tuple[ArtifactStatus, ...]:
    """Inspect all result, model, and figure artifacts."""

    managed: dict[str, Path] = dict(RESULT_TABLES)
    managed.update(
        {
            "Held-out predictions": HELD_OUT_PREDICTIONS_FILE,
            "Independent predictions": INDEPENDENT_PREDICTIONS_FILE,
            "Independent test features": INDEPENDENT_TEST_FEATURES_FILE,
            "Model metadata": MODEL_METADATA_FILE,
            "Threshold policy": THRESHOLD_FILE,
            "Feature order": FEATURE_ORDER_FILE,
        }
    )

    if FIGURES_DIR.is_dir():
        for path in sorted(FIGURES_DIR.glob("*.png")):
            managed[f"Figure: {path.stem}"] = path

    statuses = []

    for name, path in managed.items():
        exists = path.is_file()

        statuses.append(
            ArtifactStatus(
                name=name,
                path=str(path.relative_to(PROJECT_ROOT)),
                exists=exists,
                bytes=path.stat().st_size if exists else 0,
                modified_at_utc=_artifact_modified_iso(path),
                row_count=_artifact_row_count(path),
                evidence_scope=(
                    _artifact_scope(path)
                    if exists
                    else "unavailable"
                ),
            )
        )

    return tuple(statuses)


def _evidence_scope_from_sources(
    model_metadata: Mapping[str, Any],
    artifacts: Sequence[ArtifactStatus],
) -> str:
    for key in (
        "evidence_scope",
        "research_scope",
        "source_research_scope",
    ):
        if model_metadata.get(key) is not None:
            return str(model_metadata[key])

    scopes = {
        artifact.evidence_scope
        for artifact in artifacts
        if artifact.exists
        and artifact.evidence_scope
        not in {"unspecified", "unavailable"}
    }

    if len(scopes) == 1:
        return next(iter(scopes))

    if len(scopes) > 1:
        return "mixed"

    return "unspecified"


def load_prediction_evidence() -> PredictionEvidence | None:
    """Load the first chart-ready label/probability table."""

    for path in PREDICTION_SOURCES:
        rows = _safe_read_csv_rows(path)

        if not rows:
            continue

        columns = rows[0].keys()
        label_column = first_existing_column(
            columns,
            LABEL_COLUMNS,
        )
        probability_column = first_existing_column(
            columns,
            PROBABILITY_COLUMNS,
        )

        if label_column is None or probability_column is None:
            continue

        usable = []

        for row in rows:
            if (
                row.get(label_column) is None
                or row.get(probability_column) is None
            ):
                continue

            probability = _finite_float(
                row.get(probability_column)
            )

            if probability is None or not 0.0 <= probability <= 1.0:
                continue

            record = dict(row)
            record[probability_column] = probability
            usable.append(record)

        if len(usable) < 2:
            continue

        labels = {
            str(row[label_column]).strip().lower()
            for row in usable
        }

        # The chart builders perform complete validation; here we only avoid
        # selecting an obvious one-class table.
        attack_tokens = {"1", "true", "attack", "malicious", "attacker"}
        benign_tokens = {"0", "false", "benign", "normal", "valid"}

        has_attack = bool(labels & attack_tokens)
        has_benign = bool(labels & benign_tokens)

        if not (has_attack and has_benign):
            continue

        scope = _artifact_scope(path)

        return PredictionEvidence(
            source=str(path.relative_to(PROJECT_ROOT)),
            row_count=len(usable),
            label_column=label_column,
            probability_column=probability_column,
            evidence_scope=scope,
            rows=tuple(usable),
        )

    return None


def build_results_snapshot() -> ResultsSnapshot:
    """Build the complete pure results-page state."""

    metrics = load_metric_values()
    thresholds = load_threshold_values()
    model_metadata = load_model_metadata()
    run_metadata = load_run_metadata()
    artifacts = build_artifact_inventory()
    predictions = load_prediction_evidence()

    evidence_scope = _evidence_scope_from_sources(
        model_metadata,
        artifacts,
    )
    warnings = []

    if not metrics:
        warnings.append(
            "No canonical performance metrics are currently available."
        )

    if predictions is None:
        warnings.append(
            "No stored two-class prediction table is available for dynamic "
            "ROC, PR, calibration, and confusion-matrix charts."
        )

    if evidence_scope in {
        "unspecified",
        "mixed",
        "development_only",
        "synthetic_demo_development_only",
        "development_or_demo",
    }:
        warnings.append(
            "The current evidence scope is not a single confirmed "
            "research-eligible source."
        )

    available_categories = {
        category: any(path.is_file() for path in paths)
        for category, paths in CATEGORY_REQUIREMENTS.items()
    }

    model_id_value = _lookup_alias(
        model_metadata,
        ("model_id", "bundle_id"),
    )
    protocol_version_value = _lookup_alias(
        model_metadata,
        ("protocol_version", "version"),
    )
    master_seed_value = _lookup_alias(
        run_metadata or model_metadata,
        ("master_seed", "seed"),
    )

    return ResultsSnapshot(
        generated_at_utc=_utc_now_iso(),
        evidence_scope=evidence_scope,
        model_id=(
            str(model_id_value)
            if model_id_value is not None
            else None
        ),
        protocol_version=(
            str(protocol_version_value)
            if protocol_version_value is not None
            else None
        ),
        master_seed=_optional_int(master_seed_value),
        metric_values=metrics,
        threshold_values=thresholds,
        model_metadata=model_metadata,
        run_metadata=run_metadata,
        artifacts=artifacts,
        prediction_evidence=predictions,
        available_categories=available_categories,
        warnings=tuple(dict.fromkeys(warnings)),
    )


def _metric_status(
    metric_name: str,
    value: Any,
) -> str:
    """Apply conservative visual semantics without making research claims."""

    number = _finite_float(value)

    if number is None:
        return "inactive"

    if metric_name in {
        "held_out_roc_auc",
        "held_out_pr_auc",
        "independent_roc_auc",
        "independent_pr_auc",
        "attack_detection_rate",
        "valid_user_acceptance_rate",
        "tag_recovery_success_rate",
    }:
        if number >= 0.90:
            return "verified"
        if number >= 0.75:
            return "warning"
        return "failed"

    if metric_name in {
        "held_out_brier_score",
        "held_out_ece",
        "attack_acceptance_rate",
        "false_reject_rate",
    }:
        if number <= 0.05:
            return "verified"
        if number <= 0.15:
            return "warning"
        return "failed"

    return "ready"


def _format_metric(metric_name: str, value: Any) -> str:
    presentation = METRIC_PRESENTATION.get(metric_name)

    if presentation is None:
        return format_value(value)

    _, kind, _ = presentation

    if kind == "percentage":
        return format_percentage(value)

    if kind == "probability":
        return format_probability(value)

    if kind == "duration":
        return format_duration(value)

    if kind == "integer":
        number = _optional_int(value)
        return f"{number:,}" if number is not None else "—"

    return format_value(value)


def _metric_items(
    snapshot: ResultsSnapshot,
) -> tuple[MetricItem, ...]:
    items = []

    for name in METRIC_PRESENTATION:
        if name not in snapshot.metric_values:
            continue

        label, _, help_text = METRIC_PRESENTATION[name]
        value = snapshot.metric_values[name]

        items.append(
            MetricItem(
                label=label,
                value=_format_metric(name, value),
                help_text=help_text,
                status=_metric_status(name, value),
            )
        )

    return tuple(items)


def _render_overview(snapshot: ResultsSnapshot) -> None:
    render_page_header(
        title="Research Results",
        subtitle=(
            "Stored FT-QuPAP correctness, security, GP, quantum-channel, "
            "retry, baseline, runtime, circuit-validation, and "
            "reproducibility evidence"
        ),
        icon="📊",
        status=(
            "verified"
            if snapshot.evidence_scope
            in {
                "research_eligible",
                "research_eligible_session_traces",
            }
            else "warning"
        ),
    )

    render_research_notice(
        (
            "This page displays stored evidence only. Development/demo "
            "tables, incomplete archives, and unknown-scope artifacts must "
            "not be reported as final paper findings."
        )
    )

    existing_count = sum(
        artifact.exists for artifact in snapshot.artifacts
    )
    total_count = len(snapshot.artifacts)

    items = (
        KeyValueItem(
            "Evidence scope",
            snapshot.evidence_scope,
            status=(
                "verified"
                if snapshot.evidence_scope
                in {
                    "research_eligible",
                    "research_eligible_session_traces",
                }
                else "warning"
            ),
        ),
        KeyValueItem(
            "Model ID",
            snapshot.model_id or "Not available",
            code=True,
        ),
        KeyValueItem(
            "Protocol version",
            snapshot.protocol_version or "Not available",
            code=True,
        ),
        KeyValueItem(
            "Master seed",
            (
                snapshot.master_seed
                if snapshot.master_seed is not None
                else "Not available"
            ),
            code=True,
        ),
        KeyValueItem(
            "Canonical metrics",
            len(snapshot.metric_values),
            status=(
                "ready"
                if snapshot.metric_values
                else "inactive"
            ),
        ),
        KeyValueItem(
            "Managed artifacts",
            f"{existing_count}/{total_count}",
            status=(
                "verified"
                if existing_count == total_count
                else "warning"
            ),
        ),
        KeyValueItem(
            "Prediction evidence",
            (
                f"{snapshot.prediction_evidence.row_count} rows"
                if snapshot.prediction_evidence is not None
                else "Not available"
            ),
            status=(
                "ready"
                if snapshot.prediction_evidence is not None
                else "inactive"
            ),
        ),
        KeyValueItem(
            "Snapshot generated",
            snapshot.generated_at_utc,
            code=True,
        ),
    )
    render_key_value_grid(items, columns=4)


def _render_metric_summary(snapshot: ResultsSnapshot) -> None:
    render_section_title(
        "Available headline metrics",
        icon="📈",
    )

    items = _metric_items(snapshot)

    if not items:
        render_empty_state(
            "No headline metrics available",
            (
                "Generate data/results/performance_metrics.csv and the "
                "required protocol evaluation tables before reporting "
                "numerical findings."
            ),
            icon="📉",
        )
        return

    render_metric_grid(
        items,
        columns=min(4, len(items)),
    )

    render_banner(
        "Interpretation rule",
        (
            "ROC-AUC and PR-AUC describe discrimination; Brier score and ECE "
            "describe probability quality; thresholded acceptance metrics "
            "describe the deployed policy. They should not be merged into a "
            "single security claim."
        ),
        status="ready",
        icon="🧠",
    )


def _prediction_arrays(
    evidence: PredictionEvidence,
) -> tuple[list[Any], list[float]]:
    labels = [
        row[evidence.label_column]
        for row in evidence.rows
    ]
    probabilities = [
        float(row[evidence.probability_column])
        for row in evidence.rows
    ]
    return labels, probabilities


def _operational_threshold(snapshot: ResultsSnapshot) -> float | None:
    value = snapshot.metric_values.get(
        "operational_threshold"
    )

    if value is None:
        value = _lookup_alias(
            snapshot.threshold_values,
            (
                "operational_threshold",
                "gp_attack_threshold",
                "minimum_operational_threshold",
            ),
        )

    number = _finite_float(value)

    if number is None or not 0.0 <= number <= 1.0:
        return None

    return number


def _render_dynamic_gp_charts(snapshot: ResultsSnapshot) -> None:
    render_section_title(
        "Dynamic GP discrimination and calibration",
        icon="🧠",
    )

    evidence = snapshot.prediction_evidence

    if evidence is None:
        render_empty_state(
            "Prediction-level evidence unavailable",
            (
                "A table containing both a supported attack-label column and "
                "a calibrated probability column is required for dynamic "
                "ROC, PR, calibration, and confusion-matrix charts."
            ),
            icon="📉",
        )
        return

    render_banner(
        "Prediction source",
        (
            f"{evidence.source} · {evidence.row_count} rows · "
            f"scope: {evidence.evidence_scope}"
        ),
        status=(
            "verified"
            if evidence.evidence_scope
            in {
                "research_eligible",
                "research_eligible_session_traces",
            }
            else "warning"
        ),
        icon="📄",
    )

    labels, probabilities = _prediction_arrays(evidence)
    threshold = _operational_threshold(snapshot)

    builders: list[tuple[str, Any]] = [
        (
            "roc",
            lambda: build_roc_curve(
                labels,
                probabilities,
                evidence_scope=evidence.evidence_scope,
            ),
        ),
        (
            "pr",
            lambda: build_precision_recall_curve(
                labels,
                probabilities,
                evidence_scope=evidence.evidence_scope,
            ),
        ),
        (
            "calibration",
            lambda: build_calibration_curve(
                labels,
                probabilities,
                evidence_scope=evidence.evidence_scope,
            ),
        ),
    ]

    if threshold is not None:
        builders.append(
            (
                "confusion",
                lambda: build_confusion_matrix(
                    labels,
                    probabilities,
                    threshold=threshold,
                    evidence_scope=evidence.evidence_scope,
                ),
            )
        )

    st = _streamlit()

    for start in range(0, len(builders), 2):
        row = builders[start : start + 2]
        columns = st.columns(len(row))

        for container, (key, builder) in zip(columns, row):
            with container:
                try:
                    render_plotly_figure(
                        builder(),
                        key=f"results_dynamic_{key}",
                    )
                except (ChartDataError, ValueError) as exc:
                    render_empty_state(
                        "Chart unavailable",
                        str(exc),
                        icon="📉",
                    )

    if threshold is None:
        render_banner(
            "Confusion matrix not generated",
            (
                "No valid deployed operational threshold was found in the "
                "stored metric or threshold-policy artifacts."
            ),
            status="warning",
            icon="⚠️",
        )


def _load_table(path: Path) -> Any | None:
    """Load a dataframe for visual exploration."""

    if not path.is_file():
        return None

    try:
        pd = _pandas()
        table = pd.read_csv(path)
    except Exception:
        return None

    if table.empty:
        return None

    # Redact column values through record conversion.
    safe_rows = sanitize_mapping(
        table.to_dict(orient="records")
    )

    if not isinstance(safe_rows, list):
        return None

    return pd.DataFrame(safe_rows)


def _render_channel_retry_baseline_charts(
    snapshot: ResultsSnapshot,
) -> None:
    render_section_title(
        "Quantum channel, retry, and baseline evidence",
        icon="⚛️",
    )

    qber_table = None

    for path in (
        QBER_STATISTICS_FILE,
        EXPERIMENT_RESULTS_FILE,
        DASHBOARD_RESULTS_FILE,
        DEMO_SESSION_LOGS_FILE,
    ):
        qber_table = _load_table(path)

        if qber_table is not None:
            break

    probability_table = None

    for path in (
        EXPERIMENT_RESULTS_FILE,
        INDEPENDENT_RESULTS_FILE,
        DASHBOARD_RESULTS_FILE,
        DEMO_SESSION_LOGS_FILE,
    ):
        candidate = _load_table(path)

        if candidate is not None and first_existing_column(
            candidate.columns,
            PROBABILITY_COLUMNS,
        ):
            probability_table = candidate
            break

    retry_table = _load_table(RETRY_RESULTS_FILE)

    if retry_table is None:
        retry_table = _load_table(EXPERIMENT_RESULTS_FILE)

    builders: list[tuple[str, Any]] = []

    if qber_table is not None:
        builders.append(
            (
                "qber",
                lambda table=qber_table: build_qber_comparison(
                    table,
                    fixed_qber_threshold=(
                        _finite_float(
                            _lookup_alias(
                                snapshot.threshold_values,
                                (
                                    "fixed_qber_threshold",
                                ),
                            )
                        )
                        or 0.11
                    ),
                ),
            )
        )

    if probability_table is not None:
        builders.append(
            (
                "attack_probability",
                lambda table=probability_table: (
                    build_attack_probability_comparison(
                        table,
                        operational_threshold=(
                            _operational_threshold(snapshot)
                            or 0.15
                        ),
                    )
                ),
            )
        )

    if retry_table is not None:
        builders.append(
            (
                "retry",
                lambda table=retry_table: build_retry_analysis(
                    table
                ),
            )
        )

    if not builders:
        render_empty_state(
            "No channel or retry chart data",
            (
                "Generate QBER, experiment, probability, or retry result "
                "tables to populate this section."
            ),
            icon="⚛️",
        )
        return

    st = _streamlit()

    for start in range(0, len(builders), 2):
        row = builders[start : start + 2]
        columns = st.columns(len(row))

        for container, (key, builder) in zip(columns, row):
            with container:
                try:
                    render_plotly_figure(
                        builder(),
                        key=f"results_{key}",
                    )
                except (
                    ChartDataError,
                    KeyError,
                    TypeError,
                    ValueError,
                ) as exc:
                    render_empty_state(
                        "Chart unavailable",
                        str(exc),
                        icon="📉",
                    )

    baseline = _load_table(BASELINE_COMPARISON_FILE)

    if baseline is not None:
        render_section_title(
            "B1/B2/B3/P1 comparison table",
            icon="🆚",
        )
        render_records_table(
            baseline.to_dict(orient="records"),
            height=420,
        )
        render_banner(
            "Comparison wording",
            (
                "Report that FT-QuPAP extends and improves the evaluated "
                "QuPAP-inspired baseline direction under the stored "
                "simulation conditions; do not claim that it universally "
                "replaces the original protocol."
            ),
            status="warning",
            icon="📝",
        )


def _render_evidence_categories(snapshot: ResultsSnapshot) -> None:
    render_section_title(
        "Required paper-evidence categories",
        icon="🗂️",
    )

    st = _streamlit()
    categories = list(CATEGORY_REQUIREMENTS.items())

    for start in range(0, len(categories), 3):
        row = categories[start : start + 3]
        columns = st.columns(len(row))

        for container, (category, paths) in zip(columns, row):
            available = [
                path
                for path in paths
                if path.is_file()
            ]
            status = (
                "verified"
                if len(available) == len(paths)
                else (
                    "warning"
                    if available
                    else "inactive"
                )
            )

            with container:
                render_banner(
                    category,
                    (
                        f"{len(available)}/{len(paths)} expected "
                        "artifact source(s) available."
                    ),
                    status=status,
                    icon="📁",
                )


def _render_saved_figures() -> None:
    render_section_title(
        "Generated result figures",
        icon="🖼️",
    )
    render_saved_figure_gallery(columns=2)


def _render_table_explorer() -> None:
    render_section_title(
        "Stored result-table explorer",
        icon="🔎",
    )

    available = {
        name: path
        for name, path in RESULT_TABLES.items()
        if path.is_file()
    }

    if not available:
        render_empty_state(
            "No result tables available",
            (
                "Execute the notebook evaluation and export steps before "
                "using the result-table explorer."
            ),
            icon="📭",
        )
        return

    st = _streamlit()
    selected_name = st.selectbox(
        "Result table",
        tuple(available),
        key="results_view_table_selector",
    )
    selected_path = available[selected_name]
    table = _load_table(selected_path)

    if table is None:
        render_empty_state(
            "Selected table is empty or unreadable",
            str(selected_path.relative_to(PROJECT_ROOT)),
            icon="⚠️",
        )
        return

    render_banner(
        selected_name,
        (
            f"{selected_path.relative_to(PROJECT_ROOT)} · "
            f"{len(table):,} row(s) · "
            f"{len(table.columns):,} column(s)"
        ),
        status="ready",
        icon="📄",
    )

    maximum_rows = st.slider(
        "Rows to display",
        min_value=10,
        max_value=min(1000, max(10, len(table))),
        value=min(100, max(10, len(table))),
        step=10,
        key="results_view_max_rows",
    )

    render_records_table(
        table.head(maximum_rows).to_dict(orient="records"),
        height=480,
    )


def _render_artifact_inventory(snapshot: ResultsSnapshot) -> None:
    render_section_title(
        "Artifact inventory and traceability",
        icon="📦",
    )

    rows = [
        artifact.to_dictionary()
        for artifact in snapshot.artifacts
    ]
    render_records_table(
        rows,
        columns=(
            "name",
            "path",
            "exists",
            "bytes",
            "row_count",
            "modified_at_utc",
            "evidence_scope",
        ),
        height=520,
    )

    existing_bytes = sum(
        artifact.bytes
        for artifact in snapshot.artifacts
        if artifact.exists
    )
    existing_count = sum(
        artifact.exists
        for artifact in snapshot.artifacts
    )

    render_key_value_grid(
        (
            KeyValueItem(
                "Available artifacts",
                f"{existing_count}/{len(snapshot.artifacts)}",
            ),
            KeyValueItem(
                "Stored bytes",
                format_bytes(existing_bytes),
            ),
            KeyValueItem(
                "Figures directory",
                str(FIGURES_DIR.relative_to(PROJECT_ROOT)),
                code=True,
            ),
            KeyValueItem(
                "Results directory",
                str(RESULTS_DIR.relative_to(PROJECT_ROOT)),
                code=True,
            ),
        ),
        columns=4,
    )


def _render_reproducibility(snapshot: ResultsSnapshot) -> None:
    render_section_title(
        "Reproducibility and interpretation boundaries",
        icon="🔒",
    )

    render_sensitive_data_notice()

    items = (
        KeyValueItem(
            "Evidence scope",
            snapshot.evidence_scope,
        ),
        KeyValueItem(
            "Model ID",
            snapshot.model_id or "Not available",
            code=True,
        ),
        KeyValueItem(
            "Master seed",
            (
                snapshot.master_seed
                if snapshot.master_seed is not None
                else "Not available"
            ),
            code=True,
        ),
        KeyValueItem(
            "Feature order file",
            (
                "Available"
                if FEATURE_ORDER_FILE.is_file()
                else "Missing"
            ),
            status=(
                "verified"
                if FEATURE_ORDER_FILE.is_file()
                else "warning"
            ),
        ),
        KeyValueItem(
            "Threshold policy file",
            (
                "Available"
                if THRESHOLD_FILE.is_file()
                else "Missing"
            ),
            status=(
                "verified"
                if THRESHOLD_FILE.is_file()
                else "warning"
            ),
        ),
        KeyValueItem(
            "Model metadata file",
            (
                "Available"
                if MODEL_METADATA_FILE.is_file()
                else "Missing"
            ),
            status=(
                "verified"
                if MODEL_METADATA_FILE.is_file()
                else "warning"
            ),
        ),
    )
    render_key_value_grid(items, columns=3)

    render_banner(
        "Simulation boundary",
        (
            "Describe complete protocol sessions as syndrome-level Steane "
            "simulation and Qiskit/Aer as representative block validation. "
            "Do not describe this dashboard as production 5G/6G deployment "
            "or a physical 1,120-qubit experiment."
        ),
        status="warning",
        icon="🧪",
    )
    render_banner(
        "GP boundary",
        (
            "P(attack) is a calibrated probability conditional on the "
            "training and evaluation distribution. It does not prove that "
            "an eavesdropper exists and does not override deterministic "
            "cryptographic or decoder failures."
        ),
        status="warning",
        icon="🧠",
    )

    safe_export = {
        "generated_at_utc": snapshot.generated_at_utc,
        "evidence_scope": snapshot.evidence_scope,
        "model_id": snapshot.model_id,
        "protocol_version": snapshot.protocol_version,
        "master_seed": snapshot.master_seed,
        "metrics": snapshot.metric_values,
        "threshold_policy": snapshot.threshold_values,
        "available_categories": snapshot.available_categories,
        "artifacts": [
            artifact.to_dictionary()
            for artifact in snapshot.artifacts
        ],
    }

    render_json_viewer(
        safe_export,
        title="Safe results manifest",
        expanded=False,
    )
    render_json_download(
        safe_export,
        filename="ft_qupap_results_manifest.json",
        label="Download safe results manifest",
        key="download_results_manifest",
    )


def _render_warnings(snapshot: ResultsSnapshot) -> None:
    if not snapshot.warnings:
        return

    render_section_title(
        "Readiness notes",
        icon="⚠️",
    )

    for warning in snapshot.warnings:
        render_banner(
            "Attention",
            warning,
            status="warning",
        )


def render() -> None:
    """Render the FT-QuPAP research-results dashboard page."""

    apply_dashboard_theme()
    snapshot = build_results_snapshot()

    _render_overview(snapshot)
    render_divider()

    _render_metric_summary(snapshot)
    _render_dynamic_gp_charts(snapshot)
    _render_channel_retry_baseline_charts(snapshot)
    _render_evidence_categories(snapshot)
    _render_saved_figures()
    _render_table_explorer()
    _render_artifact_inventory(snapshot)
    _render_reproducibility(snapshot)
    _render_warnings(snapshot)

    st = _streamlit()
    st.caption(
        (
            "All displayed values are loaded from stored project artifacts. "
            "Missing values remain unavailable and are never replaced by "
            "illustrative numbers."
        )
    )


def results_view_status() -> dict[str, Any]:
    """Return pure diagnostics for tests and application startup."""

    snapshot = build_results_snapshot()

    return {
        "evidence_scope": snapshot.evidence_scope,
        "model_id": snapshot.model_id,
        "metric_count": len(snapshot.metric_values),
        "artifact_count": len(snapshot.artifacts),
        "available_artifact_count": sum(
            artifact.exists
            for artifact in snapshot.artifacts
        ),
        "prediction_evidence_available": (
            snapshot.prediction_evidence is not None
        ),
        "prediction_row_count": (
            snapshot.prediction_evidence.row_count
            if snapshot.prediction_evidence is not None
            else 0
        ),
        "available_category_count": sum(
            snapshot.available_categories.values()
        ),
        "warning_count": len(snapshot.warnings),
        "sensitive_material_displayed": False,
    }


__all__ = [
    "ArtifactStatus",
    "BASELINE_COMPARISON_FILE",
    "CALIBRATION_RESULTS_FILE",
    "CATEGORY_REQUIREMENTS",
    "CONFUSION_MATRIX_FILE",
    "EXPERIMENT_RESULTS_FILE",
    "HELD_OUT_PREDICTIONS_FILE",
    "INDEPENDENT_PREDICTIONS_FILE",
    "MODEL_METADATA_FILE",
    "PERFORMANCE_METRICS_FILE",
    "PredictionEvidence",
    "QBER_STATISTICS_FILE",
    "QISKIT_VALIDATION_FILE",
    "RESULTS_DIR",
    "RESULT_TABLES",
    "RETRY_RESULTS_FILE",
    "RUNTIME_STATISTICS_FILE",
    "ResultsSnapshot",
    "ResultsViewError",
    "THRESHOLD_ANALYSIS_FILE",
    "THRESHOLD_FILE",
    "build_artifact_inventory",
    "build_results_snapshot",
    "load_metric_values",
    "load_model_metadata",
    "load_prediction_evidence",
    "load_run_metadata",
    "load_threshold_values",
    "render",
    "results_view_status",
]