"""
Signed M2 server-package construction for FT-QuPAP v5.1.

After receiving and validating the Mobile Station's M1 request, the
Authentication Server prepares an M2 package containing:

- Protocol and server identity
- Session and attempt identifiers
- Mobile Station pseudonym binding
- Fresh Authentication Server nonce
- Ephemeral ML-KEM public-key package
- Encrypted quantum control schedule
- Issue and expiration timestamps
- Optional transcript binding
- ML-DSA signing-key information

The complete unsigned package is serialized canonically and signed using
the Authentication Server's long-term ML-DSA private key.

The Mobile Station must verify the ML-DSA signature before using the
ML-KEM public key or encrypted control schedule.
"""

from __future__ import annotations

import hashlib
import hmac
from dataclasses import dataclass
from tempfile import TemporaryDirectory
from pathlib import Path
from typing import Any, Mapping

from src.authentication_server.mldsa_key_manager import (
    MLDSAKeyManager,
    MLDSA_SIGNING_CONTEXT,
    get_default_mldsa_key_manager,
)

from src.common.constants import (
    PROTOCOL_DOMAIN_LABEL,
    SERVER_ID,
)

from src.common.exceptions import (
    ProtocolValidationError,
)

from src.common.serialization import (
    canonical_json_bytes,
    decode_base64,
    encode_base64,
)

from src.common.time_utils import (
    current_timestamp,
)

from src.common.validators import (
    validate_bytes,
    validate_integer,
    validate_non_empty_string,
    validate_pseudonym_id,
)


# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

SERVER_PACKAGE_VERSION = "FT-QuPAP-Server-Package-v1"

SERVER_PACKAGE_MESSAGE_TYPE = "M2"

SERVER_PACKAGE_SIGNING_CONTEXT = (
    MLDSA_SIGNING_CONTEXT
    + b":M2-Server-Package"
)

DEFAULT_SERVER_PACKAGE_TTL_SECONDS = 120

MINIMUM_SERVER_PACKAGE_TTL_SECONDS = 10

MAXIMUM_SERVER_PACKAGE_TTL_SECONDS = 3600

DEFAULT_FUTURE_TOLERANCE_SECONDS = 5

SERVER_PACKAGE_FINGERPRINT_ALGORITHM = "SHA3-256"


# ---------------------------------------------------------------------
# Local exception
# ---------------------------------------------------------------------

class ServerPackageSigningError(RuntimeError):
    """Raised when an M2 server package cannot be created or verified."""

    def __init__(
        self,
        message: str,
        *,
        details: Mapping[str, Any] | None = None,
    ) -> None:
        super().__init__(message)

        self.details = (
            {}
            if details is None
            else dict(details)
        )


# ---------------------------------------------------------------------
# Result models
# ---------------------------------------------------------------------

@dataclass(frozen=True)
class SignedServerPackage:
    """
    Complete signed FT-QuPAP M2 server package.

    Attributes
    ----------
    unsigned_package:
        Canonical package fields covered by the ML-DSA signature.

    signature:
        ML-DSA signature generated by the Authentication Server.

    package_fingerprint:
        SHA3-256 fingerprint of the canonical unsigned package.

    signing_key_id:
        Identifier of the server ML-DSA key used for signing.
    """

    unsigned_package: dict[str, Any]

    signature: bytes

    package_fingerprint: str

    signing_key_id: str
    signing_algorithm: str

    issued_at: int
    expires_at: int

    def __post_init__(self) -> None:
        if not isinstance(
            self.unsigned_package,
            dict,
        ):
            raise ProtocolValidationError(
                "unsigned_package must be a dictionary."
            )

        validate_bytes(
            self.signature,
            field_name="mldsa_signature",
            minimum_length=32,
            maximum_length=100_000,
        )

        _validate_hex_digest(
            self.package_fingerprint,
            field_name="package_fingerprint",
        )

        validate_non_empty_string(
            self.signing_key_id,
            field_name="signing_key_id",
            minimum_length=8,
            maximum_length=128,
        )

        validate_non_empty_string(
            self.signing_algorithm,
            field_name="signing_algorithm",
            minimum_length=1,
            maximum_length=64,
        )

        validate_integer(
            self.issued_at,
            field_name="issued_at",
            minimum=0,
        )

        validate_integer(
            self.expires_at,
            field_name="expires_at",
            minimum=0,
        )

        if self.expires_at <= self.issued_at:
            raise ProtocolValidationError(
                (
                    "Server-package expiration must be "
                    "later than its issue timestamp."
                )
            )

        expected_fingerprint = (
            calculate_server_package_fingerprint(
                self.unsigned_package
            )
        )

        if not hmac.compare_digest(
            self.package_fingerprint.lower(),
            expected_fingerprint,
        ):
            raise ProtocolValidationError(
                (
                    "Server-package fingerprint does not "
                    "match the unsigned package."
                )
            )

        package_issued_at = self.unsigned_package.get(
            "issued_at"
        )

        package_expires_at = self.unsigned_package.get(
            "expires_at"
        )

        if (
            package_issued_at != self.issued_at
            or package_expires_at != self.expires_at
        ):
            raise ProtocolValidationError(
                (
                    "Result timestamps do not match the "
                    "unsigned package timestamps."
                )
            )

    def to_dict(self) -> dict[str, Any]:
        """
        Return the complete network-safe signed package.
        """

        result = dict(
            self.unsigned_package
        )

        result.update(
            {
                "package_fingerprint": (
                    self.package_fingerprint
                ),
                "signature": encode_base64(
                    self.signature
                ),
            }
        )

        return result

    def __repr__(self) -> str:
        return (
            "SignedServerPackage("
            f"message_type="
            f"{self.unsigned_package.get('message_type')!r}, "
            f"session_id="
            f"{self.unsigned_package.get('session_id')!r}, "
            f"attempt_number="
            f"{self.unsigned_package.get('attempt_number')!r}, "
            f"signing_key_id={self.signing_key_id!r}, "
            f"signing_algorithm={self.signing_algorithm!r}, "
            f"package_fingerprint="
            f"{self.package_fingerprint!r}, "
            f"issued_at={self.issued_at}, "
            f"expires_at={self.expires_at}, "
            "signature=<hidden>"
            ")"
        )


@dataclass(frozen=True)
class ServerPackageVerificationResult:
    """
    Result of signed M2 server-package verification.
    """

    valid: bool

    signature_valid: bool
    fingerprint_valid: bool
    validity_period_valid: bool
    structure_valid: bool

    session_id: str | None
    attempt_number: int | None

    signing_key_id: str | None
    package_fingerprint: str | None

    checked_at: int

    message: str

    details: dict[str, Any]

    def __post_init__(self) -> None:
        for field_name in (
            "valid",
            "signature_valid",
            "fingerprint_valid",
            "validity_period_valid",
            "structure_valid",
        ):
            if not isinstance(
                getattr(
                    self,
                    field_name,
                ),
                bool,
            ):
                raise ProtocolValidationError(
                    f"{field_name} must be Boolean."
                )

        expected_valid = all(
            (
                self.signature_valid,
                self.fingerprint_valid,
                self.validity_period_valid,
                self.structure_valid,
            )
        )

        if self.valid != expected_valid:
            raise ProtocolValidationError(
                (
                    "Server-package valid flag does not "
                    "match its individual checks."
                )
            )

        if self.session_id is not None:
            validate_non_empty_string(
                self.session_id,
                field_name="session_id",
                minimum_length=3,
                maximum_length=256,
            )

        if self.attempt_number is not None:
            validate_integer(
                self.attempt_number,
                field_name="attempt_number",
                minimum=1,
                maximum=100,
            )

        if self.signing_key_id is not None:
            validate_non_empty_string(
                self.signing_key_id,
                field_name="signing_key_id",
                minimum_length=8,
                maximum_length=128,
            )

        if self.package_fingerprint is not None:
            _validate_hex_digest(
                self.package_fingerprint,
                field_name="package_fingerprint",
            )

        validate_integer(
            self.checked_at,
            field_name="checked_at",
            minimum=0,
        )

        if not isinstance(
            self.message,
            str,
        ):
            raise ProtocolValidationError(
                "Verification message must be a string."
            )

        if not isinstance(
            self.details,
            dict,
        ):
            raise ProtocolValidationError(
                "Verification details must be a dictionary."
            )

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-compatible verification result."""

        return {
            "valid": self.valid,
            "signature_valid": self.signature_valid,
            "fingerprint_valid": (
                self.fingerprint_valid
            ),
            "validity_period_valid": (
                self.validity_period_valid
            ),
            "structure_valid": self.structure_valid,
            "session_id": self.session_id,
            "attempt_number": self.attempt_number,
            "signing_key_id": self.signing_key_id,
            "package_fingerprint": (
                self.package_fingerprint
            ),
            "checked_at": self.checked_at,
            "message": self.message,
            "details": dict(
                self.details
            ),
        }


# ---------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------

def _validate_hex_digest(
    value: str,
    *,
    field_name: str,
) -> str:
    """Validate a 32-byte hexadecimal digest."""

    validated = validate_non_empty_string(
        value,
        field_name=field_name,
        minimum_length=64,
        maximum_length=64,
    ).lower()

    try:
        bytes.fromhex(
            validated
        )

    except ValueError as exc:
        raise ProtocolValidationError(
            f"{field_name} must be hexadecimal text."
        ) from exc

    return validated


def normalize_server_nonce(
    nonce: bytes | str,
) -> bytes:
    """
    Normalize a fresh Authentication Server nonce.

    Accepted representations:

    - Raw bytes
    - Hexadecimal string
    """

    if isinstance(
        nonce,
        bytes,
    ):
        return validate_bytes(
            nonce,
            field_name="server_nonce",
            minimum_length=16,
            maximum_length=64,
        )

    if not isinstance(
        nonce,
        str,
    ):
        raise ProtocolValidationError(
            (
                "server_nonce must be raw bytes or "
                "hexadecimal text."
            )
        )

    normalized_text = validate_non_empty_string(
        nonce,
        field_name="server_nonce",
        minimum_length=32,
        maximum_length=128,
    ).strip()

    if len(normalized_text) % 2 != 0:
        raise ProtocolValidationError(
            "Hexadecimal server_nonce must have an even length."
        )

    try:
        nonce_bytes = bytes.fromhex(
            normalized_text
        )

    except ValueError as exc:
        raise ProtocolValidationError(
            "server_nonce contains invalid hexadecimal text."
        ) from exc

    return validate_bytes(
        nonce_bytes,
        field_name="server_nonce",
        minimum_length=16,
        maximum_length=64,
    )


def normalize_transcript_binding(
    transcript_binding: bytes | str | None,
) -> str | None:
    """
    Normalize an optional transcript digest.

    The result is hexadecimal SHA3-256 text.
    """

    if transcript_binding is None:
        return None

    if isinstance(
        transcript_binding,
        bytes,
    ):
        validated = validate_bytes(
            transcript_binding,
            field_name="transcript_binding",
            exact_length=32,
        )

        return validated.hex()

    return _validate_hex_digest(
        transcript_binding,
        field_name="transcript_binding",
    )


def validate_mlkem_public_package(
    package: Mapping[str, Any],
    *,
    session_id: str,
    attempt_number: int,
) -> dict[str, Any]:
    """
    Validate the public ML-KEM package generated for this attempt.
    """

    if not isinstance(
        package,
        Mapping,
    ):
        raise ProtocolValidationError(
            "mlkem_public_package must be a mapping."
        )

    required_fields = (
        "session_id",
        "attempt_number",
        "algorithm",
        "key_id",
        "public_key_fingerprint",
        "public_key",
        "created_at",
        "expires_at",
    )

    missing_fields = [
        field_name
        for field_name in required_fields
        if field_name not in package
    ]

    if missing_fields:
        raise ProtocolValidationError(
            "ML-KEM public package is incomplete.",
            details={
                "missing_fields": missing_fields,
            },
        )

    normalized = dict(
        package
    )

    if normalized["session_id"] != session_id:
        raise ProtocolValidationError(
            (
                "ML-KEM public package session ID "
                "does not match the server package."
            )
        )

    if normalized["attempt_number"] != attempt_number:
        raise ProtocolValidationError(
            (
                "ML-KEM public package attempt number "
                "does not match the server package."
            )
        )

    validate_non_empty_string(
        normalized["algorithm"],
        field_name="mlkem_algorithm",
        minimum_length=1,
        maximum_length=64,
    )

    validate_non_empty_string(
        normalized["key_id"],
        field_name="mlkem_key_id",
        minimum_length=8,
        maximum_length=128,
    )

    _validate_hex_digest(
        normalized[
            "public_key_fingerprint"
        ],
        field_name=(
            "mlkem_public_key_fingerprint"
        ),
    )

    validate_non_empty_string(
        normalized["public_key"],
        field_name="mlkem_public_key",
        minimum_length=16,
        maximum_length=200_000,
    )

    created_at = validate_integer(
        normalized["created_at"],
        field_name="mlkem_created_at",
        minimum=0,
    )

    expires_at = validate_integer(
        normalized["expires_at"],
        field_name="mlkem_expires_at",
        minimum=0,
    )

    if expires_at <= created_at:
        raise ProtocolValidationError(
            (
                "ML-KEM public-key expiration must "
                "be later than its creation timestamp."
            )
        )

    return normalized


def validate_control_schedule_envelope(
    envelope: Mapping[str, Any],
) -> dict[str, Any]:
    """
    Validate the encrypted control-schedule envelope.

    The precise envelope fields are produced by the corresponding
    control-schedule encryption component. This function requires the
    authenticated-encryption fields needed by the receiver.
    """

    if not isinstance(
        envelope,
        Mapping,
    ):
        raise ProtocolValidationError(
            (
                "encrypted_control_schedule must "
                "be a mapping."
            )
        )

    required_fields = (
        "algorithm",
        "nonce",
        "ciphertext",
    )

    missing_fields = [
        field_name
        for field_name in required_fields
        if field_name not in envelope
    ]

    if missing_fields:
        raise ProtocolValidationError(
            (
                "Encrypted control-schedule "
                "envelope is incomplete."
            ),
            details={
                "missing_fields": missing_fields,
            },
        )

    normalized = dict(
        envelope
    )

    validate_non_empty_string(
        normalized["algorithm"],
        field_name=(
            "control_schedule_algorithm"
        ),
        minimum_length=1,
        maximum_length=64,
    )

    validate_non_empty_string(
        normalized["nonce"],
        field_name=(
            "control_schedule_nonce"
        ),
        minimum_length=8,
        maximum_length=10_000,
    )

    validate_non_empty_string(
        normalized["ciphertext"],
        field_name=(
            "control_schedule_ciphertext"
        ),
        minimum_length=8,
        maximum_length=10_000_000,
    )

    if "tag" in normalized:
        validate_non_empty_string(
            normalized["tag"],
            field_name="control_schedule_tag",
            minimum_length=8,
            maximum_length=10_000,
        )

    return normalized


# ---------------------------------------------------------------------
# Package construction
# ---------------------------------------------------------------------

def build_unsigned_server_package(
    *,
    session_id: str,
    attempt_number: int,
    pseudonym_id: str,
    server_nonce: bytes | str,
    mlkem_public_package: Mapping[str, Any],
    encrypted_control_schedule: Mapping[str, Any],
    signing_key_information: Mapping[str, Any],
    issued_at: int | None = None,
    ttl_seconds: int = (
        DEFAULT_SERVER_PACKAGE_TTL_SECONDS
    ),
    transcript_binding: bytes | str | None = None,
    server_id: str = SERVER_ID,
    metadata: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """
    Build the canonical unsigned M2 server package.
    """

    validated_session_id = (
        validate_non_empty_string(
            session_id,
            field_name="session_id",
            minimum_length=3,
            maximum_length=256,
        )
    )

    validated_attempt = validate_integer(
        attempt_number,
        field_name="attempt_number",
        minimum=1,
        maximum=100,
    )

    validated_pseudonym = (
        validate_pseudonym_id(
            pseudonym_id
        )
    )

    validated_server_id = (
        validate_non_empty_string(
            server_id,
            field_name="server_id",
            minimum_length=1,
            maximum_length=256,
        )
    )

    normalized_nonce = normalize_server_nonce(
        server_nonce
    )

    selected_issued_at = (
        current_timestamp()
        if issued_at is None
        else validate_integer(
            issued_at,
            field_name="issued_at",
            minimum=0,
        )
    )

    validated_ttl = validate_integer(
        ttl_seconds,
        field_name="ttl_seconds",
        minimum=(
            MINIMUM_SERVER_PACKAGE_TTL_SECONDS
        ),
        maximum=(
            MAXIMUM_SERVER_PACKAGE_TTL_SECONDS
        ),
    )

    expires_at = (
        selected_issued_at
        + validated_ttl
    )

    normalized_mlkem_package = (
        validate_mlkem_public_package(
            mlkem_public_package,
            session_id=validated_session_id,
            attempt_number=validated_attempt,
        )
    )

    normalized_schedule = (
        validate_control_schedule_envelope(
            encrypted_control_schedule
        )
    )

    if not isinstance(
        signing_key_information,
        Mapping,
    ):
        raise ProtocolValidationError(
            (
                "signing_key_information must "
                "be a mapping."
            )
        )

    required_signing_fields = (
        "algorithm",
        "key_id",
        "fingerprint",
    )

    missing_signing_fields = [
        field_name
        for field_name
        in required_signing_fields
        if field_name
        not in signing_key_information
    ]

    if missing_signing_fields:
        raise ProtocolValidationError(
            (
                "ML-DSA signing-key information "
                "is incomplete."
            ),
            details={
                "missing_fields": (
                    missing_signing_fields
                ),
            },
        )

    signing_algorithm = (
        validate_non_empty_string(
            signing_key_information[
                "algorithm"
            ],
            field_name="mldsa_algorithm",
            minimum_length=1,
            maximum_length=64,
        )
    )

    signing_key_id = (
        validate_non_empty_string(
            signing_key_information[
                "key_id"
            ],
            field_name="mldsa_key_id",
            minimum_length=8,
            maximum_length=128,
        )
    )

    signing_fingerprint = (
        _validate_hex_digest(
            signing_key_information[
                "fingerprint"
            ],
            field_name=(
                "mldsa_public_key_fingerprint"
            ),
        )
    )

    normalized_transcript_binding = (
        normalize_transcript_binding(
            transcript_binding
        )
    )

    normalized_metadata = (
        {}
        if metadata is None
        else dict(metadata)
    )

    package: dict[str, Any] = {
        "version": SERVER_PACKAGE_VERSION,

        "protocol_domain": (
            PROTOCOL_DOMAIN_LABEL.decode(
                "utf-8",
                errors="strict",
            )
        ),

        "message_type": (
            SERVER_PACKAGE_MESSAGE_TYPE
        ),

        "server_id": validated_server_id,

        "session_id": (
            validated_session_id
        ),

        "attempt_number": (
            validated_attempt
        ),

        "pseudonym_id": (
            validated_pseudonym
        ),

        "server_nonce": encode_base64(
            normalized_nonce
        ),

        "issued_at": selected_issued_at,
        "expires_at": expires_at,

        "mlkem_public_package": (
            normalized_mlkem_package
        ),

        "encrypted_control_schedule": (
            normalized_schedule
        ),

        "signing_key": {
            "algorithm": signing_algorithm,
            "key_id": signing_key_id,
            "fingerprint": (
                signing_fingerprint
            ),
        },

        "metadata": normalized_metadata,
    }

    if normalized_transcript_binding is not None:
        package["transcript_binding"] = (
            normalized_transcript_binding
        )

    return package


def calculate_server_package_fingerprint(
    unsigned_package: Mapping[str, Any],
) -> str:
    """
    Calculate the SHA3-256 canonical package fingerprint.
    """

    if not isinstance(
        unsigned_package,
        Mapping,
    ):
        raise ProtocolValidationError(
            "unsigned_package must be a mapping."
        )

    encoded_package = canonical_json_bytes(
        dict(
            unsigned_package
        )
    )

    return hashlib.sha3_256(
        encoded_package
    ).hexdigest()


# ---------------------------------------------------------------------
# Signing
# ---------------------------------------------------------------------

def sign_server_package(
    *,
    session_id: str,
    attempt_number: int,
    pseudonym_id: str,
    server_nonce: bytes | str,
    mlkem_public_package: Mapping[str, Any],
    encrypted_control_schedule: Mapping[str, Any],
    key_manager: MLDSAKeyManager | None = None,
    issued_at: int | None = None,
    ttl_seconds: int = (
        DEFAULT_SERVER_PACKAGE_TTL_SECONDS
    ),
    transcript_binding: bytes | str | None = None,
    server_id: str = SERVER_ID,
    metadata: Mapping[str, Any] | None = None,
) -> SignedServerPackage:
    """
    Build and ML-DSA-sign an M2 server package.
    """

    selected_key_manager = (
        get_default_mldsa_key_manager()
        if key_manager is None
        else key_manager
    )

    if not isinstance(
        selected_key_manager,
        MLDSAKeyManager,
    ):
        raise ProtocolValidationError(
            (
                "key_manager must be an "
                "MLDSAKeyManager object."
            )
        )

    signing_information = (
        selected_key_manager
        .get_public_information()
    )

    unsigned_package = (
        build_unsigned_server_package(
            session_id=session_id,
            attempt_number=attempt_number,
            pseudonym_id=pseudonym_id,
            server_nonce=server_nonce,
            mlkem_public_package=(
                mlkem_public_package
            ),
            encrypted_control_schedule=(
                encrypted_control_schedule
            ),
            signing_key_information=(
                signing_information
            ),
            issued_at=issued_at,
            ttl_seconds=ttl_seconds,
            transcript_binding=(
                transcript_binding
            ),
            server_id=server_id,
            metadata=metadata,
        )
    )

    canonical_package = (
        canonical_json_bytes(
            unsigned_package
        )
    )

    try:
        signature = (
            selected_key_manager.sign(
                canonical_package,
                context=(
                    SERVER_PACKAGE_SIGNING_CONTEXT
                ),
            )
        )

    except Exception as exc:
        raise ServerPackageSigningError(
            (
                "Authentication Server ML-DSA "
                "package signing failed."
            ),
            details={
                "session_id": session_id,
                "attempt_number": (
                    attempt_number
                ),
                "reason": str(exc),
            },
        ) from exc

    package_fingerprint = (
        calculate_server_package_fingerprint(
            unsigned_package
        )
    )

    return SignedServerPackage(
        unsigned_package=unsigned_package,
        signature=signature,
        package_fingerprint=(
            package_fingerprint
        ),
        signing_key_id=(
            signing_information[
                "key_id"
            ]
        ),
        signing_algorithm=(
            signing_information[
                "algorithm"
            ]
        ),
        issued_at=(
            unsigned_package[
                "issued_at"
            ]
        ),
        expires_at=(
            unsigned_package[
                "expires_at"
            ]
        ),
    )


# ---------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------

def extract_unsigned_server_package(
    signed_package: Mapping[str, Any],
) -> tuple[
    dict[str, Any],
    bytes,
    str,
]:
    """
    Separate the unsigned fields, signature, and fingerprint.
    """

    if not isinstance(
        signed_package,
        Mapping,
    ):
        raise ProtocolValidationError(
            "signed_package must be a mapping."
        )

    required_fields = (
        "signature",
        "package_fingerprint",
    )

    missing_fields = [
        field_name
        for field_name in required_fields
        if field_name not in signed_package
    ]

    if missing_fields:
        raise ProtocolValidationError(
            "Signed server package is incomplete.",
            details={
                "missing_fields": missing_fields,
            },
        )

    unsigned_package = dict(
        signed_package
    )

    encoded_signature = unsigned_package.pop(
        "signature"
    )

    package_fingerprint = unsigned_package.pop(
        "package_fingerprint"
    )

    try:
        signature = decode_base64(
            encoded_signature
        )

    except Exception as exc:
        raise ProtocolValidationError(
            (
                "Unable to decode the server-package "
                "ML-DSA signature."
            )
        ) from exc

    validate_bytes(
        signature,
        field_name="mldsa_signature",
        minimum_length=32,
        maximum_length=100_000,
    )

    normalized_fingerprint = (
        _validate_hex_digest(
            package_fingerprint,
            field_name=(
                "package_fingerprint"
            ),
        )
    )

    return (
        unsigned_package,
        signature,
        normalized_fingerprint,
    )


def verify_signed_server_package(
    signed_package: Mapping[str, Any],
    *,
    key_manager: MLDSAKeyManager | None = None,
    public_key: bytes | None = None,
    checked_at: int | None = None,
    future_tolerance_seconds: int = (
        DEFAULT_FUTURE_TOLERANCE_SECONDS
    ),
) -> ServerPackageVerificationResult:
    """
    Verify the structure, fingerprint, validity period, and signature.

    The Authentication Server may use this for self-checking. The Mobile
    Station can use the equivalent logic with the trusted ML-DSA public
    key.
    """

    selected_timestamp = (
        current_timestamp()
        if checked_at is None
        else validate_integer(
            checked_at,
            field_name="checked_at",
            minimum=0,
        )
    )

    validated_future_tolerance = (
        validate_integer(
            future_tolerance_seconds,
            field_name=(
                "future_tolerance_seconds"
            ),
            minimum=0,
            maximum=3600,
        )
    )

    selected_key_manager = (
        get_default_mldsa_key_manager()
        if key_manager is None
        else key_manager
    )

    structure_valid = False
    fingerprint_valid = False
    validity_period_valid = False
    signature_valid = False

    session_id: str | None = None
    attempt_number: int | None = None
    signing_key_id: str | None = None
    package_fingerprint: str | None = None

    details: dict[str, Any] = {}

    try:
        (
            unsigned_package,
            signature,
            package_fingerprint,
        ) = extract_unsigned_server_package(
            signed_package
        )

        required_unsigned_fields = (
            "version",
            "protocol_domain",
            "message_type",
            "server_id",
            "session_id",
            "attempt_number",
            "pseudonym_id",
            "server_nonce",
            "issued_at",
            "expires_at",
            "mlkem_public_package",
            "encrypted_control_schedule",
            "signing_key",
        )

        missing_unsigned_fields = [
            field_name
            for field_name
            in required_unsigned_fields
            if field_name
            not in unsigned_package
        ]

        if missing_unsigned_fields:
            raise ProtocolValidationError(
                (
                    "Unsigned server package is "
                    "missing required fields."
                ),
                details={
                    "missing_fields": (
                        missing_unsigned_fields
                    ),
                },
            )

        if (
            unsigned_package["version"]
            != SERVER_PACKAGE_VERSION
        ):
            raise ProtocolValidationError(
                (
                    "Unsupported server-package "
                    "version."
                )
            )

        if (
            unsigned_package[
                "message_type"
            ]
            != SERVER_PACKAGE_MESSAGE_TYPE
        ):
            raise ProtocolValidationError(
                (
                    "Invalid server-package "
                    "message type."
                )
            )

        expected_domain = (
            PROTOCOL_DOMAIN_LABEL.decode(
                "utf-8",
                errors="strict",
            )
        )

        if (
            unsigned_package[
                "protocol_domain"
            ]
            != expected_domain
        ):
            raise ProtocolValidationError(
                (
                    "Server-package protocol "
                    "domain mismatch."
                )
            )

        session_id = (
            validate_non_empty_string(
                unsigned_package[
                    "session_id"
                ],
                field_name="session_id",
                minimum_length=3,
                maximum_length=256,
            )
        )

        attempt_number = (
            validate_integer(
                unsigned_package[
                    "attempt_number"
                ],
                field_name="attempt_number",
                minimum=1,
                maximum=100,
            )
        )

        validate_pseudonym_id(
            unsigned_package[
                "pseudonym_id"
            ]
        )

        normalize_server_nonce(
            decode_base64(
                unsigned_package[
                    "server_nonce"
                ]
            )
        )

        validate_mlkem_public_package(
            unsigned_package[
                "mlkem_public_package"
            ],
            session_id=session_id,
            attempt_number=attempt_number,
        )

        validate_control_schedule_envelope(
            unsigned_package[
                "encrypted_control_schedule"
            ]
        )

        signing_information = (
            unsigned_package[
                "signing_key"
            ]
        )

        if not isinstance(
            signing_information,
            Mapping,
        ):
            raise ProtocolValidationError(
                (
                    "signing_key must be "
                    "a mapping."
                )
            )

        signing_key_id = (
            validate_non_empty_string(
                signing_information[
                    "key_id"
                ],
                field_name="signing_key_id",
                minimum_length=8,
                maximum_length=128,
            )
        )

        issued_at = validate_integer(
            unsigned_package[
                "issued_at"
            ],
            field_name="issued_at",
            minimum=0,
        )

        expires_at = validate_integer(
            unsigned_package[
                "expires_at"
            ],
            field_name="expires_at",
            minimum=0,
        )

        if expires_at <= issued_at:
            raise ProtocolValidationError(
                (
                    "Server-package validity "
                    "period is invalid."
                )
            )

        structure_valid = True

        calculated_fingerprint = (
            calculate_server_package_fingerprint(
                unsigned_package
            )
        )

        fingerprint_valid = (
            hmac.compare_digest(
                calculated_fingerprint,
                package_fingerprint,
            )
        )

        validity_period_valid = (
            selected_timestamp
            >= (
                issued_at
                - validated_future_tolerance
            )
            and selected_timestamp
            <= expires_at
        )

        canonical_package = (
            canonical_json_bytes(
                unsigned_package
            )
        )

        signature_valid = (
            selected_key_manager.verify(
                canonical_package,
                signature,
                public_key=public_key,
                context=(
                    SERVER_PACKAGE_SIGNING_CONTEXT
                ),
            )
        )

        details.update(
            {
                "issued_at": issued_at,
                "expires_at": expires_at,
                "calculated_fingerprint": (
                    calculated_fingerprint
                ),
            }
        )

    except Exception as exc:
        details["error"] = str(
            exc
        )

        details["error_type"] = type(
            exc
        ).__name__

    valid = all(
        (
            structure_valid,
            fingerprint_valid,
            validity_period_valid,
            signature_valid,
        )
    )

    if valid:
        message = (
            "The signed FT-QuPAP server package "
            "is valid."
        )

    elif not structure_valid:
        message = (
            "The FT-QuPAP server-package "
            "structure is invalid."
        )

    elif not fingerprint_valid:
        message = (
            "The FT-QuPAP server-package "
            "fingerprint is invalid."
        )

    elif not validity_period_valid:
        message = (
            "The FT-QuPAP server package is "
            "expired or not yet valid."
        )

    else:
        message = (
            "The FT-QuPAP server-package "
            "ML-DSA signature is invalid."
        )

    return ServerPackageVerificationResult(
        valid=valid,
        signature_valid=signature_valid,
        fingerprint_valid=(
            fingerprint_valid
        ),
        validity_period_valid=(
            validity_period_valid
        ),
        structure_valid=structure_valid,
        session_id=session_id,
        attempt_number=attempt_number,
        signing_key_id=signing_key_id,
        package_fingerprint=(
            package_fingerprint
        ),
        checked_at=selected_timestamp,
        message=message,
        details=details,
    )


def require_valid_server_package(
    signed_package: Mapping[str, Any],
    *,
    key_manager: MLDSAKeyManager | None = None,
    public_key: bytes | None = None,
    checked_at: int | None = None,
) -> ServerPackageVerificationResult:
    """
    Verify a signed server package and raise when invalid.
    """

    result = verify_signed_server_package(
        signed_package,
        key_manager=key_manager,
        public_key=public_key,
        checked_at=checked_at,
    )

    if not result.valid:
        raise ServerPackageSigningError(
            result.message,
            details=result.to_dict(),
        )

    return result


# ---------------------------------------------------------------------
# Self-test
# ---------------------------------------------------------------------

def run_server_package_signer_self_test() -> dict[str, Any]:
    """
    Test M2 construction, signing, verification, tamper detection,
    and expiration rejection.
    """

    try:
        with TemporaryDirectory() as directory:
            root = Path(
                directory
            )

            key_manager = MLDSAKeyManager(
                public_key_path=(
                    root / "mldsa-public.json"
                ),
                secret_key_path=(
                    root / "mldsa-secret.json"
                ),
            )

            key_manager.generate_keypair()

            session_id = (
                "FTQ-SERVER-PACKAGE-SELF-TEST"
            )

            attempt_number = 1

            mlkem_public_package = {
                "session_id": session_id,
                "attempt_number": (
                    attempt_number
                ),
                "algorithm": "ML-KEM-768",
                "key_id": (
                    "MLKEM-SELF-TEST-KEY-00000001"
                ),
                "public_key_fingerprint": (
                    hashlib.sha3_256(
                        b"P" * 64
                    ).hexdigest()
                ),
                "public_key": encode_base64(
                    b"P" * 64
                ),
                "created_at": 1_700_000_000,
                "expires_at": 1_700_000_120,
            }

            encrypted_control_schedule = {
                "version": (
                    "FT-QuPAP-Control-Schedule-v1"
                ),
                "algorithm": "AES-256-GCM",
                "nonce": encode_base64(
                    b"N" * 12
                ),
                "ciphertext": encode_base64(
                    b"C" * 128
                ),
                "tag": encode_base64(
                    b"T" * 16
                ),
            }

            signed_result = sign_server_package(
                session_id=session_id,
                attempt_number=attempt_number,
                pseudonym_id=(
                    "PID-FTQ-SERVER-PACKAGE-001"
                ),
                server_nonce=(
                    b"S" * 32
                ),
                mlkem_public_package=(
                    mlkem_public_package
                ),
                encrypted_control_schedule=(
                    encrypted_control_schedule
                ),
                key_manager=key_manager,
                issued_at=1_700_000_000,
                ttl_seconds=120,
                transcript_binding=(
                    b"H" * 32
                ),
                metadata={
                    "context": "urban",
                },
            )

            network_package = (
                signed_result.to_dict()
            )

            verification_result = (
                verify_signed_server_package(
                    network_package,
                    key_manager=key_manager,
                    checked_at=1_700_000_050,
                )
            )

            tampered_package = dict(
                network_package
            )

            tampered_package[
                "attempt_number"
            ] = 2

            tampered_result = (
                verify_signed_server_package(
                    tampered_package,
                    key_manager=key_manager,
                    checked_at=1_700_000_050,
                )
            )

            expired_result = (
                verify_signed_server_package(
                    network_package,
                    key_manager=key_manager,
                    checked_at=1_700_000_121,
                )
            )

            secret_fields_absent = all(
                field_name
                not in network_package
                for field_name in (
                    "secret_key",
                    "mlkem_secret_key",
                    "mldsa_secret_key",
                )
            )

            success = all(
                (
                    verification_result.valid,
                    verification_result
                    .signature_valid,
                    verification_result
                    .fingerprint_valid,
                    verification_result
                    .validity_period_valid,

                    not tampered_result.valid,

                    (
                        not tampered_result
                        .signature_valid
                        or not tampered_result
                        .fingerprint_valid
                        or not tampered_result
                        .structure_valid
                    ),

                    not expired_result.valid,

                    not expired_result
                    .validity_period_valid,

                    secret_fields_absent,
                )
            )

            return {
                "success": success,

                "package_version": (
                    network_package[
                        "version"
                    ]
                ),

                "message_type": (
                    network_package[
                        "message_type"
                    ]
                ),

                "session_id": (
                    network_package[
                        "session_id"
                    ]
                ),

                "attempt_number": (
                    network_package[
                        "attempt_number"
                    ]
                ),

                "package_fingerprint": (
                    signed_result
                    .package_fingerprint
                ),

                "signature_bytes": len(
                    signed_result.signature
                ),

                "valid_package_accepted": (
                    verification_result.valid
                ),

                "valid_signature": (
                    verification_result
                    .signature_valid
                ),

                "tampered_package_rejected": (
                    not tampered_result.valid
                ),

                "expired_package_rejected": (
                    not expired_result.valid
                ),

                "secret_fields_absent": (
                    secret_fields_absent
                ),
            }

    except Exception as exc:
        return {
            "success": False,
            "error": str(exc),
            "error_type": type(
                exc
            ).__name__,
        }


__all__ = [
    "SERVER_PACKAGE_VERSION",
    "SERVER_PACKAGE_MESSAGE_TYPE",
    "SERVER_PACKAGE_SIGNING_CONTEXT",
    "DEFAULT_SERVER_PACKAGE_TTL_SECONDS",
    "SERVER_PACKAGE_FINGERPRINT_ALGORITHM",
    "ServerPackageSigningError",
    "SignedServerPackage",
    "ServerPackageVerificationResult",
    "normalize_server_nonce",
    "normalize_transcript_binding",
    "validate_mlkem_public_package",
    "validate_control_schedule_envelope",
    "build_unsigned_server_package",
    "calculate_server_package_fingerprint",
    "sign_server_package",
    "extract_unsigned_server_package",
    "verify_signed_server_package",
    "require_valid_server_package",
    "run_server_package_signer_self_test",
]