#!/usr/bin/env python3
"""
Validate the exported FT-QuPAP Gaussian Process model bundle.

This script is the independent deployment gate for the artifacts created by
scripts/export_gp_model.py. It does not train, tune, recalibrate, or overwrite
the detector. It verifies that the Authentication Server can safely load and
use the model bundle required by flowchart Steps 17-19:

    Step 17: construct the nine observable GP features,
    Step 18: estimate calibrated P(attack),
    Step 19: apply accept / retry / reject thresholds.

Validated model bundle:
    models/gp_model.pkl
    models/feature_scaler.pkl
    models/calibration_model.pkl
    models/threshold.json
    models/feature_order.json
    models/model_metadata.json

Optional cross-check inputs:
    data/processed/independent_test_features.csv
    data/results/performance_metrics.csv
    data/results/confusion_matrix.csv

Main checks:
    1. Required files exist and are non-empty.
    2. JSON files are valid and mutually consistent.
    3. Model-file SHA-256 hashes match model_metadata.json.
    4. Exported feature order exactly matches the notebook schema.
    5. StandardScaler, GaussianProcessClassifier, and IsotonicRegression
       objects have compatible dimensions and fitted attributes.
    6. Thresholds obey the FT-QuPAP accept/retry/reject policy.
    7. A single-row and batch inference smoke test produce finite P(attack)
       values in [0, 1].
    8. The isotonic calibrator is monotonic.
    9. When the held-out test split exists, metrics and confusion counts are
       independently recomputed and compared with exported result files.
   10. The model ID is recomputed from the artifact hashes and policy data.

Security note:
    joblib/pickle files can execute code while loading. Validate only model
    files generated by this project or obtained from a fully trusted source.

Run from the project root:
    python scripts/validate_model_files.py

Useful options:
    python scripts/validate_model_files.py --strict
    python scripts/validate_model_files.py --sample-rows 128
    python scripts/validate_model_files.py --skip-dataset-check
    python scripts/validate_model_files.py --report outputs/reports/model_validation_report.json
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata as importlib_metadata
import json
import logging
import math
import os
import platform
import sys
import tempfile
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import joblib
import numpy as np
import pandas as pd
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.isotonic import IsotonicRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    balanced_accuracy_score,
    brier_score_loss,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import StandardScaler


PROJECT_ROOT = Path(__file__).resolve().parents[1]

MODEL_DIR = PROJECT_ROOT / "models"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
RESULTS_DIR = PROJECT_ROOT / "data" / "results"
LOG_DIR = PROJECT_ROOT / "outputs" / "logs"
REPORT_DIR = PROJECT_ROOT / "outputs" / "reports"

GP_MODEL_FILE = MODEL_DIR / "gp_model.pkl"
FEATURE_SCALER_FILE = MODEL_DIR / "feature_scaler.pkl"
CALIBRATION_MODEL_FILE = MODEL_DIR / "calibration_model.pkl"
THRESHOLD_FILE = MODEL_DIR / "threshold.json"
FEATURE_ORDER_FILE = MODEL_DIR / "feature_order.json"
MODEL_METADATA_FILE = MODEL_DIR / "model_metadata.json"

INDEPENDENT_TEST_FILE = PROCESSED_DIR / "independent_test_features.csv"
PERFORMANCE_METRICS_FILE = RESULTS_DIR / "performance_metrics.csv"
CONFUSION_MATRIX_FILE = RESULTS_DIR / "confusion_matrix.csv"

LOG_FILE = LOG_DIR / "validate_model_files.log"
DEFAULT_REPORT_FILE = REPORT_DIR / "model_validation_report.json"

PROTOCOL_NAME = "FT-QuPAP"
EXPECTED_PROTOCOL_VERSION = (
    "research-simulator-v5-1-large-ml-operational-threshold"
)
EXPECTED_SCHEMA_VERSION = 1

EXPECTED_FEATURE_ORDER = [
    "qber_raw",
    "mean_syndrome_weight",
    "max_syndrome_weight",
    "correction_failure_rate",
    "loss_rate",
    "noise_estimate",
    "ctx_urban",
    "ctx_suburban",
    "ctx_rural",
]

LABEL_COLUMN = "label_attack"

REQUIRED_MODEL_FILES = (
    GP_MODEL_FILE,
    FEATURE_SCALER_FILE,
    CALIBRATION_MODEL_FILE,
    THRESHOLD_FILE,
    FEATURE_ORDER_FILE,
    MODEL_METADATA_FILE,
)

DEFAULT_SAMPLE_ROWS = 64
DEFAULT_METRIC_ABSOLUTE_TOLERANCE = 1e-9
DEFAULT_THRESHOLD_ABSOLUTE_TOLERANCE = 1e-12


class ValidationFailure(RuntimeError):
    """Raised when model validation cannot be completed."""


@dataclass(frozen=True)
class ValidationIssue:
    """One validation warning or error."""

    severity: str
    check: str
    message: str


@dataclass
class ValidationReport:
    """Complete machine-readable validation outcome."""

    protocol: str = PROTOCOL_NAME
    validation_started_utc: str = ""
    validation_finished_utc: str = ""
    project_root: str = ""
    strict_mode: bool = False
    dataset_check_enabled: bool = True
    status: str = "RUNNING"
    model_id: str | None = None
    evidence_scope: str | None = None
    checks_passed: list[str] = field(default_factory=list)
    issues: list[ValidationIssue] = field(default_factory=list)
    artifact_details: dict[str, Any] = field(default_factory=dict)
    threshold_details: dict[str, Any] = field(default_factory=dict)
    inference_details: dict[str, Any] = field(default_factory=dict)
    metric_details: dict[str, Any] = field(default_factory=dict)
    runtime: dict[str, Any] = field(default_factory=dict)

    def add_pass(self, check: str) -> None:
        """Record a successful validation check once."""

        if check not in self.checks_passed:
            self.checks_passed.append(check)

    def add_warning(self, check: str, message: str) -> None:
        """Record a non-fatal validation warning."""

        self.issues.append(
            ValidationIssue(
                severity="WARNING",
                check=check,
                message=message,
            )
        )

    def add_error(self, check: str, message: str) -> None:
        """Record a fatal validation error."""

        self.issues.append(
            ValidationIssue(
                severity="ERROR",
                check=check,
                message=message,
            )
        )

    @property
    def errors(self) -> list[ValidationIssue]:
        return [
            issue
            for issue in self.issues
            if issue.severity == "ERROR"
        ]

    @property
    def warnings(self) -> list[ValidationIssue]:
        return [
            issue
            for issue in self.issues
            if issue.severity == "WARNING"
        ]

    def finalize(self) -> None:
        """Derive the final report status."""

        self.validation_finished_utc = utc_now_iso()

        if self.errors:
            self.status = "FAIL"
        elif self.strict_mode and self.warnings:
            self.status = "FAIL_STRICT"
        elif self.warnings:
            self.status = "PASS_WITH_WARNINGS"
        else:
            self.status = "PASS"

    def to_dictionary(self) -> dict[str, Any]:
        """Convert nested dataclasses to JSON-compatible data."""

        return asdict(self)


def utc_now_iso() -> str:
    """Return a stable timezone-aware UTC timestamp."""

    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def configure_logging() -> logging.Logger:
    """Configure console and persistent validation logging."""

    LOG_DIR.mkdir(parents=True, exist_ok=True)

    logger = logging.getLogger("ft_qupap.validate_model_files")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()

    formatter = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s"
    )

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)

    file_handler = logging.FileHandler(LOG_FILE, encoding="utf-8")
    file_handler.setFormatter(formatter)

    logger.addHandler(console_handler)
    logger.addHandler(file_handler)
    return logger


def parse_arguments() -> argparse.Namespace:
    """Parse command-line validation options."""

    parser = argparse.ArgumentParser(
        description=(
            "Validate the exported FT-QuPAP GP detector, calibrator, "
            "threshold policy, metadata, and held-out inference behavior."
        )
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Treat validation warnings as a non-zero exit status.",
    )
    parser.add_argument(
        "--sample-rows",
        type=int,
        default=DEFAULT_SAMPLE_ROWS,
        help=(
            "Maximum held-out rows used for the batch inference smoke test "
            f"(default: {DEFAULT_SAMPLE_ROWS})."
        ),
    )
    parser.add_argument(
        "--skip-dataset-check",
        action="store_true",
        help=(
            "Validate only the model bundle; skip held-out metric and "
            "result-file cross-checks."
        ),
    )
    parser.add_argument(
        "--metric-tolerance",
        type=float,
        default=DEFAULT_METRIC_ABSOLUTE_TOLERANCE,
        help=(
            "Absolute tolerance for exported metric comparisons "
            f"(default: {DEFAULT_METRIC_ABSOLUTE_TOLERANCE})."
        ),
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=DEFAULT_REPORT_FILE,
        help=(
            "JSON validation-report destination, relative paths being "
            "resolved from the project root."
        ),
    )
    parser.add_argument(
        "--no-report",
        action="store_true",
        help="Do not write the JSON validation report.",
    )
    return parser.parse_args()


def validate_arguments(args: argparse.Namespace) -> None:
    """Reject invalid validator settings."""

    if args.sample_rows < 1:
        raise ValidationFailure("--sample-rows must be at least 1.")

    if (
        not math.isfinite(args.metric_tolerance)
        or args.metric_tolerance < 0.0
    ):
        raise ValidationFailure(
            "--metric-tolerance must be a finite non-negative value."
        )


def resolve_report_path(path: Path) -> Path:
    """Resolve a report path relative to the project root."""

    if path.is_absolute():
        return path
    return PROJECT_ROOT / path


def sha256_file(path: Path) -> str:
    """Return the SHA-256 digest of one file."""

    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def atomic_write_text(path: Path, content: str) -> None:
    """Atomically write a UTF-8 text file."""

    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
    )
    temporary_path = Path(temporary_name)

    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_path, path)
    except Exception:
        temporary_path.unlink(missing_ok=True)
        raise


def atomic_write_json(path: Path, payload: Any) -> None:
    """Atomically write deterministic human-readable JSON."""

    atomic_write_text(
        path,
        json.dumps(
            payload,
            indent=2,
            sort_keys=True,
            ensure_ascii=False,
        )
        + "\n",
    )


def load_json(path: Path) -> Any:
    """Load one required JSON file with an actionable error."""

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ValidationFailure(
            f"Required JSON artifact is missing: {path}"
        ) from exc
    except json.JSONDecodeError as exc:
        raise ValidationFailure(
            f"Invalid JSON in {path}: {exc}"
        ) from exc


def installed_version(distribution: str) -> str | None:
    """Return the local version of an installed Python distribution."""

    try:
        return importlib_metadata.version(distribution)
    except importlib_metadata.PackageNotFoundError:
        return None


def numeric_close(
    left: float,
    right: float,
    tolerance: float,
) -> bool:
    """Compare finite numeric values with an absolute tolerance."""

    return (
        math.isfinite(float(left))
        and math.isfinite(float(right))
        and math.isclose(
            float(left),
            float(right),
            rel_tol=0.0,
            abs_tol=tolerance,
        )
    )


def record_exception(
    report: ValidationReport,
    check: str,
    exc: Exception,
) -> None:
    """Convert an unexpected check exception into one report error."""

    report.add_error(check, f"{type(exc).__name__}: {exc}")


def validate_required_files(
    report: ValidationReport,
) -> dict[str, str]:
    """Check model-bundle presence, size, and calculate local hashes."""

    check = "required_model_files"
    local_hashes: dict[str, str] = {}

    for path in REQUIRED_MODEL_FILES:
        relative_name = str(path.relative_to(PROJECT_ROOT))

        if not path.is_file():
            report.add_error(check, f"Missing file: {relative_name}")
            continue

        size = path.stat().st_size
        if size <= 0:
            report.add_error(check, f"Empty file: {relative_name}")
            continue

        digest = sha256_file(path)
        local_hashes[relative_name] = digest
        report.artifact_details[relative_name] = {
            "bytes": size,
            "sha256": digest,
        }

    if not report.errors:
        report.add_pass(check)

    return local_hashes


def validate_feature_schema(
    report: ValidationReport,
    feature_order: Any,
    metadata: Mapping[str, Any],
) -> list[str]:
    """Validate the nine server-observable GP feature columns."""

    check = "feature_schema"

    if not isinstance(feature_order, list):
        report.add_error(
            check,
            "feature_order.json must contain a JSON array.",
        )
        return []

    if not all(isinstance(item, str) for item in feature_order):
        report.add_error(
            check,
            "Every feature-order entry must be a string.",
        )
        return []

    if feature_order != EXPECTED_FEATURE_ORDER:
        report.add_error(
            check,
            "Feature order does not match the FT-QuPAP notebook schema. "
            f"Expected {EXPECTED_FEATURE_ORDER}; received {feature_order}.",
        )

    metadata_features = metadata.get("feature_order")
    if metadata_features != feature_order:
        report.add_error(
            check,
            "model_metadata.json and feature_order.json disagree.",
        )

    forbidden_inputs = {
        "scenario",
        "scenario_severity",
        "eve_fraction",
        "eve_mode",
        "actual_attack",
        LABEL_COLUMN,
    }
    leaked = sorted(forbidden_inputs.intersection(feature_order))
    if leaked:
        report.add_error(
            check,
            "Hidden simulator/label fields leaked into model input: "
            f"{leaked}",
        )

    if not any(
        issue.check == check and issue.severity == "ERROR"
        for issue in report.issues
    ):
        report.add_pass(check)

    return list(feature_order)


def validate_metadata_identity(
    report: ValidationReport,
    metadata: Mapping[str, Any],
    feature_order: Sequence[str],
    local_hashes: Mapping[str, str],
) -> None:
    """Validate protocol identity, hashes, schema, and model ID."""

    check = "metadata_identity"

    if metadata.get("protocol") != PROTOCOL_NAME:
        report.add_error(
            check,
            "Unexpected protocol identity in model_metadata.json: "
            f"{metadata.get('protocol')!r}",
        )

    if metadata.get("protocol_version") != EXPECTED_PROTOCOL_VERSION:
        report.add_warning(
            check,
            "Protocol version differs from the current v5.1 notebook: "
            f"{metadata.get('protocol_version')!r}",
        )

    if metadata.get("schema_version") != EXPECTED_SCHEMA_VERSION:
        report.add_error(
            check,
            "Unsupported model metadata schema version: "
            f"{metadata.get('schema_version')!r}",
        )

    probability_semantics = metadata.get("probability_semantics")
    if probability_semantics != "P(attack)":
        report.add_error(
            check,
            "Model probability semantics must be 'P(attack)'.",
        )

    recorded_hashes = metadata.get("artifacts")
    if not isinstance(recorded_hashes, Mapping):
        report.add_error(
            check,
            "model_metadata.json must contain an artifacts hash map.",
        )
        recorded_hashes = {}

    for relative_name, expected_hash in recorded_hashes.items():
        if not isinstance(relative_name, str):
            report.add_error(
                check,
                "Artifact hash-map keys must be relative path strings.",
            )
            continue

        artifact_path = PROJECT_ROOT / relative_name
        if not artifact_path.is_file():
            report.add_error(
                check,
                f"Metadata references a missing file: {relative_name}",
            )
            continue

        actual_hash = local_hashes.get(relative_name)
        if actual_hash is None:
            actual_hash = sha256_file(artifact_path)

        if actual_hash != expected_hash:
            report.add_error(
                check,
                f"SHA-256 mismatch for {relative_name}.",
            )

    required_hashed_artifacts = {
        str(GP_MODEL_FILE.relative_to(PROJECT_ROOT)),
        str(FEATURE_SCALER_FILE.relative_to(PROJECT_ROOT)),
        str(CALIBRATION_MODEL_FILE.relative_to(PROJECT_ROOT)),
        str(THRESHOLD_FILE.relative_to(PROJECT_ROOT)),
        str(FEATURE_ORDER_FILE.relative_to(PROJECT_ROOT)),
    }
    missing_hash_entries = sorted(
        required_hashed_artifacts - set(recorded_hashes)
    )
    if missing_hash_entries:
        report.add_error(
            check,
            "Metadata is missing required artifact hashes: "
            f"{missing_hash_entries}",
        )

    threshold_policy = metadata.get("threshold_policy", {})
    operational_threshold = threshold_policy.get(
        "operational_threshold"
    )

    try:
        identity_material = json.dumps(
            {
                "artifact_hashes": dict(
                    sorted(
                        (
                            str(name),
                            str(digest),
                        )
                        for name, digest in recorded_hashes.items()
                    )
                ),
                "feature_order": list(feature_order),
                "operational_threshold": float(
                    operational_threshold
                ),
                "protocol_version": metadata.get(
                    "protocol_version"
                ),
            },
            sort_keys=True,
        ).encode("utf-8")
        recomputed_model_id = hashlib.sha256(
            identity_material
        ).hexdigest()[:24]
        recorded_model_id = metadata.get("model_id")

        report.model_id = (
            str(recorded_model_id)
            if recorded_model_id is not None
            else None
        )

        if recomputed_model_id != recorded_model_id:
            report.add_error(
                check,
                "model_id does not match the exported artifact hashes "
                "and threshold policy.",
            )
    except (TypeError, ValueError) as exc:
        report.add_error(
            check,
            f"Unable to recompute model_id: {exc}",
        )

    report.evidence_scope = metadata.get("evidence_scope")
    if report.evidence_scope == "synthetic_demo_development_only":
        report.add_warning(
            check,
            "This model was trained from synthetic development/demo "
            "fixtures and must not be presented as final research evidence.",
        )
    elif report.evidence_scope in {
        "source_scope_unspecified",
        "mixed_or_partially_specified",
        None,
    }:
        report.add_warning(
            check,
            "The training evidence scope is not fully established.",
        )

    if not any(
        issue.check == check and issue.severity == "ERROR"
        for issue in report.issues
    ):
        report.add_pass(check)


def finite_probability(
    report: ValidationReport,
    check: str,
    name: str,
    value: Any,
) -> float | None:
    """Validate and return one probability field."""

    try:
        probability = float(value)
    except (TypeError, ValueError):
        report.add_error(
            check,
            f"{name} is not numeric: {value!r}",
        )
        return None

    if not math.isfinite(probability):
        report.add_error(
            check,
            f"{name} must be finite.",
        )
        return None

    if not 0.0 <= probability <= 1.0:
        report.add_error(
            check,
            f"{name} must be between 0 and 1; found {probability}.",
        )
        return None

    return probability


def validate_threshold_policy(
    report: ValidationReport,
    threshold_data: Mapping[str, Any],
    metadata: Mapping[str, Any],
) -> dict[str, float]:
    """Validate flowchart Step 19 accept/retry/reject boundaries."""

    check = "threshold_policy"

    raw_threshold = finite_probability(
        report,
        check,
        "raw_calibrated_threshold",
        threshold_data.get("raw_calibrated_threshold"),
    )
    minimum_threshold = finite_probability(
        report,
        check,
        "minimum_operational_threshold",
        threshold_data.get("minimum_operational_threshold"),
    )
    operational_threshold = finite_probability(
        report,
        check,
        "operational_threshold",
        threshold_data.get("operational_threshold"),
    )
    retry_upper = finite_probability(
        report,
        check,
        "retry_upper_probability",
        threshold_data.get("retry_upper_probability"),
    )
    fixed_qber_threshold = finite_probability(
        report,
        check,
        "fixed_qber_threshold",
        threshold_data.get("fixed_qber_threshold"),
    )
    maximum_loss_rate = finite_probability(
        report,
        check,
        "maximum_loss_rate",
        threshold_data.get("maximum_loss_rate"),
    )

    if (
        raw_threshold is not None
        and minimum_threshold is not None
        and operational_threshold is not None
    ):
        expected_operational = max(
            raw_threshold,
            minimum_threshold,
        )
        if not numeric_close(
            operational_threshold,
            expected_operational,
            DEFAULT_THRESHOLD_ABSOLUTE_TOLERANCE,
        ):
            report.add_error(
                check,
                "Operational threshold must equal "
                "max(raw_calibrated_threshold, "
                "minimum_operational_threshold).",
            )

    if (
        operational_threshold is not None
        and retry_upper is not None
    ):
        if retry_upper < operational_threshold:
            report.add_warning(
                check,
                "Retry gray zone is inactive because its upper probability "
                "is below the operational threshold. This can occur when "
                "the calibration-selected threshold exceeds 0.20; normal "
                "accept/reject inference remains valid, but GP gray-zone "
                "retry cannot be reached for this model bundle.",
            )
        elif numeric_close(
            retry_upper,
            operational_threshold,
            DEFAULT_THRESHOLD_ABSOLUTE_TOLERANCE,
        ):
            report.add_warning(
                check,
                "Retry gray zone has zero width.",
            )

    if (
        threshold_data.get("probability_semantics")
        != "P(attack)"
    ):
        report.add_error(
            check,
            "threshold.json probability semantics must be 'P(attack)'.",
        )

    expected_rules = {
        "accept_rule": "p_attack < operational_threshold",
        "reject_rule": "p_attack >= operational_threshold",
    }
    for field_name, expected_value in expected_rules.items():
        if threshold_data.get(field_name) != expected_value:
            report.add_warning(
                check,
                f"{field_name} differs from the exporter contract.",
            )

    minimum_observed = threshold_data.get(
        "minimum_observed_check_blocks"
    )
    maximum_attempts = threshold_data.get(
        "maximum_authentication_attempts"
    )

    if not isinstance(minimum_observed, int) or minimum_observed < 1:
        report.add_error(
            check,
            "minimum_observed_check_blocks must be a positive integer.",
        )

    if not isinstance(maximum_attempts, int) or maximum_attempts < 1:
        report.add_error(
            check,
            "maximum_authentication_attempts must be a positive integer.",
        )

    metadata_policy = metadata.get("threshold_policy")
    if not isinstance(metadata_policy, Mapping):
        report.add_error(
            check,
            "model_metadata.json threshold_policy is missing.",
        )
        metadata_policy = {}

    comparable_fields = (
        "raw_calibrated_threshold",
        "minimum_operational_threshold",
        "operational_threshold",
        "retry_upper_probability",
        "fixed_qber_threshold",
        "maximum_loss_rate",
        "minimum_observed_check_blocks",
        "maximum_authentication_attempts",
        "cost_false_accept",
        "cost_false_reject",
    )

    for field_name in comparable_fields:
        left = threshold_data.get(field_name)
        right = metadata_policy.get(field_name)

        if isinstance(left, (int, float)) and isinstance(
            right,
            (int, float),
        ):
            if not numeric_close(
                float(left),
                float(right),
                DEFAULT_THRESHOLD_ABSOLUTE_TOLERANCE,
            ):
                report.add_error(
                    check,
                    f"Threshold mismatch for {field_name}.",
                )
        elif left != right:
            report.add_error(
                check,
                f"Threshold mismatch for {field_name}.",
            )

    report.threshold_details = {
        "raw_calibrated_threshold": raw_threshold,
        "minimum_operational_threshold": minimum_threshold,
        "operational_threshold": operational_threshold,
        "retry_upper_probability": retry_upper,
        "fixed_qber_threshold": fixed_qber_threshold,
        "maximum_loss_rate": maximum_loss_rate,
        "minimum_observed_check_blocks": minimum_observed,
        "maximum_authentication_attempts": maximum_attempts,
    }

    if not any(
        issue.check == check and issue.severity == "ERROR"
        for issue in report.issues
    ):
        report.add_pass(check)

    return {
        key: float(value)
        for key, value in {
            "raw_calibrated_threshold": raw_threshold,
            "minimum_operational_threshold": minimum_threshold,
            "operational_threshold": operational_threshold,
            "retry_upper_probability": retry_upper,
        }.items()
        if value is not None
    }


def fitted_attribute_exists(
    value: Any,
    attribute_name: str,
) -> bool:
    """Return whether a fitted scikit-learn attribute exists."""

    return hasattr(value, attribute_name) and getattr(
        value,
        attribute_name,
    ) is not None


def validate_loaded_objects(
    report: ValidationReport,
    feature_order: Sequence[str],
) -> tuple[
    StandardScaler | None,
    GaussianProcessClassifier | None,
    IsotonicRegression | None,
]:
    """Load trusted local joblib files and validate object compatibility."""

    check = "serialized_model_objects"

    try:
        scaler = joblib.load(FEATURE_SCALER_FILE)
        model = joblib.load(GP_MODEL_FILE)
        calibrator = joblib.load(CALIBRATION_MODEL_FILE)
    except Exception as exc:
        report.add_error(
            check,
            f"Unable to load serialized model files: {exc}",
        )
        return None, None, None

    if not isinstance(scaler, StandardScaler):
        report.add_error(
            check,
            "feature_scaler.pkl is not a StandardScaler.",
        )

    if not isinstance(model, GaussianProcessClassifier):
        report.add_error(
            check,
            "gp_model.pkl is not a GaussianProcessClassifier.",
        )

    if not isinstance(calibrator, IsotonicRegression):
        report.add_error(
            check,
            "calibration_model.pkl is not an IsotonicRegression.",
        )

    expected_count = len(feature_order)

    if isinstance(scaler, StandardScaler):
        if not fitted_attribute_exists(scaler, "mean_"):
            report.add_error(
                check,
                "StandardScaler is not fitted.",
            )
        elif len(np.asarray(scaler.mean_)) != expected_count:
            report.add_error(
                check,
                "StandardScaler feature dimension does not match "
                "feature_order.json.",
            )

        scaler_count = getattr(scaler, "n_features_in_", None)
        if scaler_count is not None and int(scaler_count) != expected_count:
            report.add_error(
                check,
                "StandardScaler.n_features_in_ is inconsistent.",
            )

    if isinstance(model, GaussianProcessClassifier):
        if not fitted_attribute_exists(model, "classes_"):
            report.add_error(
                check,
                "GaussianProcessClassifier is not fitted.",
            )
        else:
            classes = set(
                np.asarray(model.classes_).astype(int).tolist()
            )
            if classes != {0, 1}:
                report.add_error(
                    check,
                    "GP classes must be exactly {0, 1}.",
                )

        model_count = getattr(model, "n_features_in_", None)
        if model_count is not None and int(model_count) != expected_count:
            report.add_error(
                check,
                "GaussianProcessClassifier.n_features_in_ is "
                "inconsistent.",
            )

    if isinstance(calibrator, IsotonicRegression):
        required_attributes = ("X_thresholds_", "y_thresholds_")
        missing = [
            name
            for name in required_attributes
            if not fitted_attribute_exists(calibrator, name)
        ]
        if missing:
            report.add_error(
                check,
                "IsotonicRegression is not fitted; missing "
                f"{missing}.",
            )

    if not any(
        issue.check == check and issue.severity == "ERROR"
        for issue in report.issues
    ):
        report.add_pass(check)

    return (
        scaler if isinstance(scaler, StandardScaler) else None,
        (
            model
            if isinstance(model, GaussianProcessClassifier)
            else None
        ),
        (
            calibrator
            if isinstance(calibrator, IsotonicRegression)
            else None
        ),
    )


def validate_calibrator_monotonicity(
    report: ValidationReport,
    calibrator: IsotonicRegression | None,
) -> None:
    """Verify that calibrated P(attack) never decreases as raw GP risk rises."""

    check = "calibrator_monotonicity"

    if calibrator is None:
        report.add_error(
            check,
            "Calibration object is unavailable.",
        )
        return

    try:
        raw_grid = np.linspace(0.0, 1.0, 1001)
        calibrated_grid = np.asarray(
            calibrator.predict(raw_grid),
            dtype=float,
        )
    except Exception as exc:
        report.add_error(
            check,
            f"Calibrator grid inference failed: {exc}",
        )
        return

    if not np.isfinite(calibrated_grid).all():
        report.add_error(
            check,
            "Calibrator produced NaN or infinite values.",
        )

    if np.any(calibrated_grid < -1e-12) or np.any(
        calibrated_grid > 1.0 + 1e-12
    ):
        report.add_error(
            check,
            "Calibrator produced probabilities outside [0, 1].",
        )

    if np.any(np.diff(calibrated_grid) < -1e-12):
        report.add_error(
            check,
            "Isotonic calibration output is not monotonic.",
        )

    report.inference_details["calibrator_grid"] = {
        "raw_min": 0.0,
        "raw_max": 1.0,
        "calibrated_min": float(np.min(calibrated_grid)),
        "calibrated_max": float(np.max(calibrated_grid)),
        "unique_calibrated_values": int(
            len(np.unique(calibrated_grid))
        ),
    }

    if not any(
        issue.check == check and issue.severity == "ERROR"
        for issue in report.issues
    ):
        report.add_pass(check)


def validate_feature_table(
    table: pd.DataFrame,
    feature_order: Sequence[str],
) -> None:
    """Validate held-out features before independent model inference."""

    required = set(feature_order) | {LABEL_COLUMN}
    missing = sorted(required - set(table.columns))
    if missing:
        raise ValidationFailure(
            f"Independent test file is missing columns: {missing}"
        )

    if table.empty:
        raise ValidationFailure(
            "Independent test feature file is empty."
        )

    numeric_features = table[list(feature_order)].apply(
        pd.to_numeric,
        errors="coerce",
    )

    if numeric_features.isna().any().any():
        bad_columns = numeric_features.columns[
            numeric_features.isna().any()
        ].tolist()
        raise ValidationFailure(
            "Independent test features contain missing/non-numeric "
            f"values in {bad_columns}."
        )

    if not np.isfinite(
        numeric_features.to_numpy(dtype=float)
    ).all():
        raise ValidationFailure(
            "Independent test features contain NaN or infinity."
        )

    labels = pd.to_numeric(
        table[LABEL_COLUMN],
        errors="coerce",
    )
    if labels.isna().any():
        raise ValidationFailure(
            "Independent test labels contain non-numeric values."
        )

    integer_labels = labels.astype(int)
    if not np.array_equal(
        labels.to_numpy(),
        integer_labels.to_numpy(),
    ):
        raise ValidationFailure(
            "Independent test labels must be integers."
        )

    if set(integer_labels.unique()) != {0, 1}:
        raise ValidationFailure(
            "Independent test split must contain labels 0 and 1."
        )

    context_columns = [
        "ctx_urban",
        "ctx_suburban",
        "ctx_rural",
    ]
    if all(column in numeric_features for column in context_columns):
        context = numeric_features[context_columns].to_numpy(
            dtype=float
        )
        if not np.isin(context, [0.0, 1.0]).all():
            raise ValidationFailure(
                "Context fields must be one-hot 0/1 values."
            )
        if not np.allclose(context.sum(axis=1), 1.0):
            raise ValidationFailure(
                "Exactly one context field must be active per row."
            )


def predict_probabilities(
    scaler: StandardScaler,
    model: GaussianProcessClassifier,
    calibrator: IsotonicRegression,
    features: pd.DataFrame,
    feature_order: Sequence[str],
) -> tuple[np.ndarray, np.ndarray]:
    """Return raw and calibrated attack probabilities."""

    transformed = scaler.transform(features[list(feature_order)])
    raw = np.asarray(
        model.predict_proba(transformed)[:, 1],
        dtype=float,
    )
    calibrated = np.asarray(
        calibrator.predict(raw),
        dtype=float,
    )

    return raw, calibrated


def validate_probability_array(
    values: np.ndarray,
    name: str,
) -> None:
    """Validate one model probability vector."""

    if values.ndim != 1:
        raise ValidationFailure(
            f"{name} must be a one-dimensional array."
        )

    if len(values) == 0:
        raise ValidationFailure(f"{name} is empty.")

    if not np.isfinite(values).all():
        raise ValidationFailure(
            f"{name} contains NaN or infinity."
        )

    if np.any(values < -1e-12) or np.any(
        values > 1.0 + 1e-12
    ):
        raise ValidationFailure(
            f"{name} contains values outside [0, 1]."
        )


def validate_inference(
    report: ValidationReport,
    scaler: StandardScaler | None,
    model: GaussianProcessClassifier | None,
    calibrator: IsotonicRegression | None,
    feature_order: Sequence[str],
    sample_rows: int,
) -> pd.DataFrame | None:
    """Run single-row and batch inference on the held-out split."""

    check = "inference_smoke_test"

    if scaler is None or model is None or calibrator is None:
        report.add_error(
            check,
            "One or more model objects are unavailable.",
        )
        return None

    if not INDEPENDENT_TEST_FILE.is_file():
        report.add_warning(
            check,
            "Independent test file is unavailable; using a neutral "
            "synthetic schema-valid smoke row only.",
        )
        neutral_row = pd.DataFrame(
            [
                {
                    "qber_raw": 0.01,
                    "mean_syndrome_weight": 0.05,
                    "max_syndrome_weight": 1.0,
                    "correction_failure_rate": 0.0,
                    "loss_rate": 0.01,
                    "noise_estimate": 0.01,
                    "ctx_urban": 1.0,
                    "ctx_suburban": 0.0,
                    "ctx_rural": 0.0,
                }
            ]
        )
        try:
            raw, calibrated = predict_probabilities(
                scaler,
                model,
                calibrator,
                neutral_row,
                feature_order,
            )
            validate_probability_array(raw, "raw probability")
            validate_probability_array(
                calibrated,
                "calibrated probability",
            )
        except Exception as exc:
            report.add_error(
                check,
                f"Neutral-row inference failed: {exc}",
            )
            return None

        report.inference_details["single_row"] = {
            "source": "neutral_schema_valid_row",
            "raw_p_attack": float(raw[0]),
            "calibrated_p_attack": float(calibrated[0]),
        }
        report.add_pass(check)
        return None

    try:
        table = pd.read_csv(INDEPENDENT_TEST_FILE)
        validate_feature_table(table, feature_order)

        batch_size = min(sample_rows, len(table))
        sample = table.sample(
            n=batch_size,
            random_state=20260701,
            replace=False,
        ).reset_index(drop=True)

        single_raw, single_calibrated = predict_probabilities(
            scaler,
            model,
            calibrator,
            sample.iloc[[0]],
            feature_order,
        )
        batch_raw, batch_calibrated = predict_probabilities(
            scaler,
            model,
            calibrator,
            sample,
            feature_order,
        )

        validate_probability_array(
            single_raw,
            "single raw probability",
        )
        validate_probability_array(
            single_calibrated,
            "single calibrated probability",
        )
        validate_probability_array(
            batch_raw,
            "batch raw probabilities",
        )
        validate_probability_array(
            batch_calibrated,
            "batch calibrated probabilities",
        )

        if len(batch_raw) != batch_size:
            raise ValidationFailure(
                "Raw GP batch length does not match input length."
            )
        if len(batch_calibrated) != batch_size:
            raise ValidationFailure(
                "Calibrated batch length does not match input length."
            )

        report.inference_details["single_row"] = {
            "source": str(
                INDEPENDENT_TEST_FILE.relative_to(PROJECT_ROOT)
            ),
            "raw_p_attack": float(single_raw[0]),
            "calibrated_p_attack": float(
                single_calibrated[0]
            ),
        }
        report.inference_details["batch"] = {
            "rows": batch_size,
            "raw_probability_min": float(np.min(batch_raw)),
            "raw_probability_max": float(np.max(batch_raw)),
            "calibrated_probability_min": float(
                np.min(batch_calibrated)
            ),
            "calibrated_probability_max": float(
                np.max(batch_calibrated)
            ),
            "calibration_changed_probability_count": int(
                np.sum(
                    ~np.isclose(
                        batch_raw,
                        batch_calibrated,
                        atol=1e-15,
                    )
                )
            ),
        }

        report.add_pass(check)
        return table

    except Exception as exc:
        record_exception(report, check, exc)
        return None


def calculate_probability_metrics(
    labels: np.ndarray,
    probabilities: np.ndarray,
) -> dict[str, float]:
    """Calculate the notebook-aligned held-out GP metrics."""

    return {
        "roc_auc": float(
            roc_auc_score(labels, probabilities)
        ),
        "pr_auc": float(
            average_precision_score(labels, probabilities)
        ),
        "brier_score": float(
            brier_score_loss(labels, probabilities)
        ),
    }


def calculate_decision_metrics(
    labels: np.ndarray,
    probabilities: np.ndarray,
    threshold: float,
) -> tuple[dict[str, float], np.ndarray]:
    """Calculate policy metrics using P(attack) >= threshold as reject."""

    predicted_attack = (probabilities >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(
        labels,
        predicted_attack,
        labels=[0, 1],
    ).ravel()

    metrics = {
        "accuracy": float(
            accuracy_score(labels, predicted_attack)
        ),
        "balanced_accuracy": float(
            balanced_accuracy_score(
                labels,
                predicted_attack,
            )
        ),
        "precision_attack": float(
            precision_score(
                labels,
                predicted_attack,
                zero_division=0,
            )
        ),
        "recall_attack": float(
            recall_score(
                labels,
                predicted_attack,
                zero_division=0,
            )
        ),
        "f1_attack": float(
            f1_score(
                labels,
                predicted_attack,
                zero_division=0,
            )
        ),
        "false_accept_rate": float(
            fn / (tp + fn)
            if (tp + fn)
            else 0.0
        ),
        "false_reject_rate": float(
            fp / (tn + fp)
            if (tn + fp)
            else 0.0
        ),
        "attack_detection_rate": float(
            tp / (tp + fn)
            if (tp + fn)
            else 0.0
        ),
        "benign_acceptance_rate": float(
            tn / (tn + fp)
            if (tn + fp)
            else 0.0
        ),
    }

    matrix = np.array(
        [
            [tn, fp],
            [fn, tp],
        ],
        dtype=int,
    )

    return metrics, matrix


def exported_metric_map(path: Path) -> dict[str, float]:
    """Read the long-form performance_metrics.csv format."""

    table = pd.read_csv(path)
    required = {"metric", "value"}
    missing = required - set(table.columns)
    if missing:
        raise ValidationFailure(
            f"{path.name} is missing columns: {sorted(missing)}"
        )

    result: dict[str, float] = {}
    for row in table.itertuples(index=False):
        metric = str(getattr(row, "metric"))
        value = float(getattr(row, "value"))
        result[metric] = value
    return result


def compare_metric_maps(
    report: ValidationReport,
    recomputed: Mapping[str, float],
    exported: Mapping[str, float],
    tolerance: float,
) -> None:
    """Compare independently calculated held-out metrics."""

    check = "heldout_metric_cross_check"

    missing = sorted(set(recomputed) - set(exported))
    if missing:
        report.add_error(
            check,
            "performance_metrics.csv is missing metrics: "
            f"{missing}",
        )

    mismatches: dict[str, dict[str, float]] = {}
    for name, actual in recomputed.items():
        if name not in exported:
            continue
        recorded = exported[name]
        if not numeric_close(actual, recorded, tolerance):
            mismatches[name] = {
                "recomputed": actual,
                "exported": recorded,
                "absolute_difference": abs(actual - recorded),
            }

    if mismatches:
        report.add_error(
            check,
            "Exported held-out metrics do not match fresh inference: "
            f"{mismatches}",
        )

    report.metric_details["metric_comparison"] = {
        "absolute_tolerance": tolerance,
        "recomputed": dict(recomputed),
        "exported": {
            name: exported.get(name)
            for name in recomputed
        },
        "mismatches": mismatches,
    }

    if not any(
        issue.check == check and issue.severity == "ERROR"
        for issue in report.issues
    ):
        report.add_pass(check)


def parse_exported_confusion_matrix(path: Path) -> np.ndarray:
    """Read the explicit confusion_matrix.csv exported by the trainer."""

    table = pd.read_csv(path)
    required = {"actual_label", "predicted_label", "count"}
    missing = required - set(table.columns)
    if missing:
        raise ValidationFailure(
            f"{path.name} is missing columns: {sorted(missing)}"
        )

    label_order = ["benign", "attack"]
    matrix = np.zeros((2, 2), dtype=int)

    for row in table.itertuples(index=False):
        actual = str(getattr(row, "actual_label"))
        predicted = str(getattr(row, "predicted_label"))
        count = int(getattr(row, "count"))

        if actual not in label_order or predicted not in label_order:
            raise ValidationFailure(
                "confusion_matrix.csv contains an unknown label."
            )

        matrix[
            label_order.index(actual),
            label_order.index(predicted),
        ] += count

    return matrix


def validate_heldout_metrics(
    report: ValidationReport,
    scaler: StandardScaler | None,
    model: GaussianProcessClassifier | None,
    calibrator: IsotonicRegression | None,
    feature_order: Sequence[str],
    threshold_values: Mapping[str, float],
    test_table: pd.DataFrame | None,
    tolerance: float,
) -> None:
    """Recompute held-out metrics and compare exported result files."""

    check = "heldout_metric_recalculation"

    if scaler is None or model is None or calibrator is None:
        report.add_error(
            check,
            "Model objects are unavailable for metric recalculation.",
        )
        return

    if test_table is None:
        report.add_warning(
            check,
            "Independent test data is unavailable; held-out metrics "
            "could not be recalculated.",
        )
        return

    operational_threshold = threshold_values.get(
        "operational_threshold"
    )
    if operational_threshold is None:
        report.add_error(
            check,
            "Operational threshold is unavailable.",
        )
        return

    try:
        raw, calibrated = predict_probabilities(
            scaler,
            model,
            calibrator,
            test_table,
            feature_order,
        )
        validate_probability_array(
            raw,
            "full-test raw probabilities",
        )
        validate_probability_array(
            calibrated,
            "full-test calibrated probabilities",
        )

        labels = (
            pd.to_numeric(
                test_table[LABEL_COLUMN],
                errors="raise",
            )
            .astype(int)
            .to_numpy()
        )

        probability_metrics = calculate_probability_metrics(
            labels,
            calibrated,
        )
        decision_metrics, matrix = calculate_decision_metrics(
            labels,
            calibrated,
            operational_threshold,
        )
        combined_metrics = {
            **probability_metrics,
            **decision_metrics,
        }

        report.metric_details[
            "independent_test_recomputed"
        ] = {
            "rows": int(len(test_table)),
            "operational_threshold": operational_threshold,
            **combined_metrics,
            "confusion_matrix": matrix.tolist(),
        }
        report.add_pass(check)

        if PERFORMANCE_METRICS_FILE.is_file():
            exported = exported_metric_map(
                PERFORMANCE_METRICS_FILE
            )
            compare_metric_maps(
                report,
                combined_metrics,
                exported,
                tolerance,
            )
        else:
            report.add_warning(
                "heldout_metric_cross_check",
                "performance_metrics.csv is unavailable.",
            )

        if CONFUSION_MATRIX_FILE.is_file():
            exported_matrix = parse_exported_confusion_matrix(
                CONFUSION_MATRIX_FILE
            )
            if not np.array_equal(matrix, exported_matrix):
                report.add_error(
                    "confusion_matrix_cross_check",
                    "confusion_matrix.csv does not match fresh inference. "
                    f"Recomputed={matrix.tolist()}, "
                    f"exported={exported_matrix.tolist()}",
                )
            else:
                report.add_pass(
                    "confusion_matrix_cross_check"
                )
        else:
            report.add_warning(
                "confusion_matrix_cross_check",
                "confusion_matrix.csv is unavailable.",
            )

    except Exception as exc:
        record_exception(report, check, exc)


def validate_runtime_compatibility(
    report: ValidationReport,
    metadata: Mapping[str, Any],
) -> None:
    """Compare important local package versions with export metadata."""

    check = "runtime_compatibility"

    local_runtime = {
        "python": platform.python_version(),
        "platform": platform.platform(),
        "numpy": installed_version("numpy"),
        "pandas": installed_version("pandas"),
        "scikit_learn": installed_version("scikit-learn"),
        "joblib": installed_version("joblib"),
    }
    report.runtime = local_runtime

    exported_runtime = metadata.get("runtime")
    if not isinstance(exported_runtime, Mapping):
        report.add_warning(
            check,
            "Export metadata does not contain runtime versions.",
        )
        return

    for field_name in (
        "numpy",
        "pandas",
        "scikit_learn",
        "joblib",
    ):
        exported_version = exported_runtime.get(field_name)
        local_version = local_runtime.get(field_name)

        if exported_version is None or local_version is None:
            continue

        if str(exported_version) != str(local_version):
            report.add_warning(
                check,
                f"{field_name} version differs: exported "
                f"{exported_version}, local {local_version}.",
            )

    report.add_pass(check)


def log_report(
    logger: logging.Logger,
    report: ValidationReport,
) -> None:
    """Write a concise human-readable validation summary to the log."""

    for check in report.checks_passed:
        logger.info("PASS | %s", check)

    for issue in report.issues:
        log_method = (
            logger.error
            if issue.severity == "ERROR"
            else logger.warning
        )
        log_method(
            "%s | %s | %s",
            issue.severity,
            issue.check,
            issue.message,
        )

    logger.info(
        "Validation status=%s passed_checks=%d warnings=%d errors=%d",
        report.status,
        len(report.checks_passed),
        len(report.warnings),
        len(report.errors),
    )


def run_validation(
    args: argparse.Namespace,
    logger: logging.Logger,
) -> ValidationReport:
    """Execute all independent model-bundle validation checks."""

    report = ValidationReport(
        validation_started_utc=utc_now_iso(),
        project_root=str(PROJECT_ROOT),
        strict_mode=bool(args.strict),
        dataset_check_enabled=not args.skip_dataset_check,
    )

    try:
        local_hashes = validate_required_files(report)

        if report.errors:
            report.finalize()
            return report

        feature_order_data = load_json(FEATURE_ORDER_FILE)
        threshold_data = load_json(THRESHOLD_FILE)
        metadata_data = load_json(MODEL_METADATA_FILE)

        if not isinstance(threshold_data, Mapping):
            report.add_error(
                "threshold_policy",
                "threshold.json must contain a JSON object.",
            )
            threshold_data = {}

        if not isinstance(metadata_data, Mapping):
            report.add_error(
                "metadata_identity",
                "model_metadata.json must contain a JSON object.",
            )
            metadata_data = {}

        feature_order = validate_feature_schema(
            report,
            feature_order_data,
            metadata_data,
        )

        validate_metadata_identity(
            report,
            metadata_data,
            feature_order,
            local_hashes,
        )

        threshold_values = validate_threshold_policy(
            report,
            threshold_data,
            metadata_data,
        )

        scaler, model, calibrator = validate_loaded_objects(
            report,
            feature_order,
        )

        validate_calibrator_monotonicity(
            report,
            calibrator,
        )

        test_table = validate_inference(
            report,
            scaler,
            model,
            calibrator,
            feature_order,
            args.sample_rows,
        )

        if not args.skip_dataset_check:
            validate_heldout_metrics(
                report,
                scaler,
                model,
                calibrator,
                feature_order,
                threshold_values,
                test_table,
                args.metric_tolerance,
            )

        validate_runtime_compatibility(
            report,
            metadata_data,
        )

    except Exception as exc:
        record_exception(
            report,
            "validation_orchestrator",
            exc,
        )

    report.finalize()
    log_report(logger, report)
    return report


def main() -> int:
    """Command-line entry point."""

    args = parse_arguments()
    logger = configure_logging()

    try:
        validate_arguments(args)
        report = run_validation(args, logger)

        report_payload = report.to_dictionary()

        if not args.no_report:
            report_path = resolve_report_path(args.report)
            atomic_write_json(report_path, report_payload)
            logger.info("Saved validation report: %s", report_path)

        print(
            json.dumps(
                report_payload,
                indent=2,
                sort_keys=True,
            )
        )

        return 0 if report.status in {
            "PASS",
            "PASS_WITH_WARNINGS",
        } else 1

    except (
        ValidationFailure,
        FileNotFoundError,
        KeyError,
        TypeError,
        ValueError,
        OSError,
    ) as exc:
        logger.error("%s", exc)
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    except Exception:
        logger.exception("Unexpected model validation failure.")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
