"""
Randomness management for the FT-QuPAP v5.1 project.

This module separates two types of randomness:

1. Cryptographic randomness
   - Nonces
   - Session identifiers
   - Control-schedule seeds
   - Other security-sensitive random values

2. Reproducible simulation randomness
   - Quantum noise simulation
   - Loss simulation
   - Eve attack selection
   - Dataset generation
   - Repeatable capstone demonstrations

Security-sensitive values use Python's `secrets` module.

Simulation values use NumPy's Generator with a controllable seed.
The seeded generator must not be used to generate real cryptographic keys.
"""

from __future__ import annotations

import hashlib
import secrets
import threading
import uuid
from dataclasses import dataclass
from typing import Sequence, TypeVar

import numpy as np

from src.common.constants import (
    NONCE_SIZE_BYTES,
    RANDOM_SEED,
)

from src.common.exceptions import (
    ConfigurationError,
    ProtocolValidationError,
)

from src.common.validators import (
    validate_integer,
    validate_probability,
)


T = TypeVar("T")


# ---------------------------------------------------------------------
# Cryptographic randomness
# ---------------------------------------------------------------------

def secure_random_bytes(length: int) -> bytes:
    """
    Generate cryptographically secure random bytes.

    This function is appropriate for:

    - Authentication nonces
    - Session salts
    - Local identifiers
    - Control-schedule protection values

    ML-KEM and ML-DSA keys should still be generated by their respective
    post-quantum cryptographic libraries.
    """

    validated_length = validate_integer(
        length,
        field_name="length",
        minimum=1,
        maximum=1_000_000,
    )

    return secrets.token_bytes(
        validated_length
    )


def generate_nonce_bytes(
    length: int = NONCE_SIZE_BYTES,
) -> bytes:
    """
    Generate a cryptographically secure nonce as raw bytes.

    The FT-QuPAP default is 16 bytes, or 128 bits.
    """

    return secure_random_bytes(length)


def generate_nonce_hex(
    length: int = NONCE_SIZE_BYTES,
) -> str:
    """
    Generate a cryptographically secure hexadecimal nonce.

    A 16-byte nonce produces 32 hexadecimal characters.
    """

    validated_length = validate_integer(
        length,
        field_name="nonce_length",
        minimum=1,
        maximum=1024,
    )

    return secrets.token_hex(
        validated_length
    )


def generate_secure_token_hex(
    byte_length: int = 32,
) -> str:
    """
    Generate a general-purpose cryptographically secure token.
    """

    validated_length = validate_integer(
        byte_length,
        field_name="byte_length",
        minimum=1,
        maximum=4096,
    )

    return secrets.token_hex(
        validated_length
    )


def generate_session_id(
    prefix: str = "FTQ",
) -> str:
    """
    Generate a unique protocol-session identifier.

    Example:

        FTQ-7B176FC0404B45C1BCE6EF8D26E5AE58
    """

    if not isinstance(prefix, str):
        raise ProtocolValidationError(
            "Session ID prefix must be a string.",
            details={
                "received_type": type(prefix).__name__,
            },
        )

    normalized_prefix = prefix.strip().upper()

    if not normalized_prefix:
        raise ProtocolValidationError(
            "Session ID prefix cannot be empty."
        )

    if len(normalized_prefix) > 32:
        raise ProtocolValidationError(
            "Session ID prefix is too long.",
            details={
                "maximum_length": 32,
                "actual_length": len(normalized_prefix),
            },
        )

    return (
        f"{normalized_prefix}-"
        f"{uuid.uuid4().hex.upper()}"
    )


def secure_random_integer(
    minimum: int,
    maximum: int,
) -> int:
    """
    Generate a cryptographically secure integer in the inclusive range.

    Example:

        secure_random_integer(1, 10)
    """

    validated_minimum = validate_integer(
        minimum,
        field_name="minimum",
    )

    validated_maximum = validate_integer(
        maximum,
        field_name="maximum",
    )

    if validated_maximum < validated_minimum:
        raise ProtocolValidationError(
            "Maximum must not be lower than minimum.",
            details={
                "minimum": validated_minimum,
                "maximum": validated_maximum,
            },
        )

    range_size = (
        validated_maximum
        - validated_minimum
        + 1
    )

    return (
        validated_minimum
        + secrets.randbelow(range_size)
    )


def secure_random_bit() -> int:
    """
    Generate one cryptographically secure classical bit.
    """

    return secrets.randbelow(2)


def secure_random_bits(count: int) -> list[int]:
    """
    Generate a list of cryptographically secure classical bits.
    """

    validated_count = validate_integer(
        count,
        field_name="count",
        minimum=0,
        maximum=10_000_000,
    )

    return [
        secure_random_bit()
        for _ in range(validated_count)
    ]


def secure_shuffle(
    values: Sequence[T],
) -> list[T]:
    """
    Return a securely shuffled copy of a sequence.

    This function uses the `secrets` module rather than NumPy's seeded
    generator.
    """

    shuffled_values = list(values)

    for current_index in range(
        len(shuffled_values) - 1,
        0,
        -1,
    ):
        selected_index = secrets.randbelow(
            current_index + 1
        )

        shuffled_values[
            current_index
        ], shuffled_values[
            selected_index
        ] = (
            shuffled_values[
                selected_index
            ],
            shuffled_values[
                current_index
            ],
        )

    return shuffled_values


# ---------------------------------------------------------------------
# Seed derivation
# ---------------------------------------------------------------------

def derive_deterministic_seed(
    *components: object,
    base_seed: int = RANDOM_SEED,
) -> int:
    """
    Derive a repeatable integer seed from multiple values.

    This is useful for controlled demonstrations where each scenario
    should produce the same result every time.

    This function is not intended for cryptographic key generation.
    """

    validated_base_seed = validate_integer(
        base_seed,
        field_name="base_seed",
        minimum=0,
    )

    digest = hashlib.sha3_256()

    digest.update(
        str(validated_base_seed).encode("utf-8")
    )

    for component in components:
        digest.update(b"\x00")
        digest.update(
            str(component).encode("utf-8")
        )

    return int.from_bytes(
        digest.digest()[:8],
        byteorder="big",
        signed=False,
    )


# ---------------------------------------------------------------------
# Reproducible simulation generator
# ---------------------------------------------------------------------

@dataclass
class SimulationRandomManager:
    """
    Thread-safe wrapper around NumPy's random Generator.

    Use this class for:

    - Channel noise
    - Qubit loss
    - Error positions
    - Eve attack selection
    - Synthetic dataset generation

    Do not use this class to generate:

    - ML-DSA keys
    - ML-KEM keys
    - Authentication nonces in real protocol mode
    """

    seed: int = RANDOM_SEED

    def __post_init__(self) -> None:
        self.seed = validate_integer(
            self.seed,
            field_name="seed",
            minimum=0,
        )

        self._generator = np.random.default_rng(
            self.seed
        )

        self._lock = threading.Lock()

    @property
    def generator(self) -> np.random.Generator:
        """
        Return the underlying NumPy generator.

        Direct use should be limited to modules that need NumPy-specific
        sampling functionality.
        """

        return self._generator

    def reset(
        self,
        seed: int | None = None,
    ) -> None:
        """
        Reset the simulation generator.

        When no seed is provided, the manager returns to its original
        configured seed.
        """

        selected_seed = (
            self.seed
            if seed is None
            else validate_integer(
                seed,
                field_name="seed",
                minimum=0,
            )
        )

        with self._lock:
            self.seed = selected_seed

            self._generator = (
                np.random.default_rng(
                    selected_seed
                )
            )

    def random(self) -> float:
        """
        Generate a floating-point value in [0, 1).
        """

        with self._lock:
            return float(
                self._generator.random()
            )

    def probability_event(
        self,
        probability: float,
    ) -> bool:
        """
        Return True with the supplied probability.
        """

        validated_probability = validate_probability(
            probability,
            field_name="probability",
        )

        if validated_probability == 0.0:
            return False

        if validated_probability == 1.0:
            return True

        return (
            self.random()
            < validated_probability
        )

    def integer(
        self,
        minimum: int,
        maximum_exclusive: int,
    ) -> int:
        """
        Generate an integer in:

            [minimum, maximum_exclusive)
        """

        validated_minimum = validate_integer(
            minimum,
            field_name="minimum",
        )

        validated_maximum = validate_integer(
            maximum_exclusive,
            field_name="maximum_exclusive",
        )

        if (
            validated_maximum
            <= validated_minimum
        ):
            raise ProtocolValidationError(
                (
                    "maximum_exclusive must be "
                    "greater than minimum."
                ),
                details={
                    "minimum": validated_minimum,
                    "maximum_exclusive": (
                        validated_maximum
                    ),
                },
            )

        with self._lock:
            return int(
                self._generator.integers(
                    validated_minimum,
                    validated_maximum,
                )
            )

    def choice(
        self,
        values: Sequence[T],
    ) -> T:
        """
        Select one element from a non-empty sequence.
        """

        if not values:
            raise ProtocolValidationError(
                "Cannot select from an empty sequence."
            )

        selected_index = self.integer(
            0,
            len(values),
        )

        return values[selected_index]

    def choice_with_probabilities(
        self,
        values: Sequence[T],
        probabilities: Sequence[float],
    ) -> T:
        """
        Select one item using explicit probabilities.
        """

        if len(values) == 0:
            raise ProtocolValidationError(
                "Values cannot be empty."
            )

        if len(values) != len(probabilities):
            raise ProtocolValidationError(
                (
                    "Values and probabilities must "
                    "have the same length."
                ),
                details={
                    "value_count": len(values),
                    "probability_count": (
                        len(probabilities)
                    ),
                },
            )

        normalized_probabilities = [
            validate_probability(
                probability,
                field_name=(
                    f"probabilities[{index}]"
                ),
            )
            for index, probability
            in enumerate(probabilities)
        ]

        probability_sum = sum(
            normalized_probabilities
        )

        if not np.isclose(
            probability_sum,
            1.0,
            rtol=0.0,
            atol=1e-9,
        ):
            raise ProtocolValidationError(
                "Selection probabilities must sum to 1.0.",
                details={
                    "probability_sum": probability_sum,
                },
            )

        with self._lock:
            selected_index = int(
                self._generator.choice(
                    len(values),
                    p=normalized_probabilities,
                )
            )

        return values[selected_index]

    def shuffle(
        self,
        values: Sequence[T],
    ) -> list[T]:
        """
        Return a reproducibly shuffled copy of a sequence.
        """

        shuffled = list(values)

        with self._lock:
            self._generator.shuffle(
                shuffled
            )

        return shuffled

    def permutation(
        self,
        size: int,
    ) -> list[int]:
        """
        Generate a reproducible permutation of integer indices.

        Example:

            permutation(4)

        may return:

            [3, 1, 0, 2]
        """

        validated_size = validate_integer(
            size,
            field_name="size",
            minimum=0,
            maximum=10_000_000,
        )

        with self._lock:
            result = self._generator.permutation(
                validated_size
            )

        return [
            int(value)
            for value in result.tolist()
        ]

    def normal(
        self,
        mean: float = 0.0,
        standard_deviation: float = 1.0,
    ) -> float:
        """
        Generate a value from a normal distribution.
        """

        if standard_deviation < 0:
            raise ProtocolValidationError(
                "Standard deviation cannot be negative.",
                details={
                    "standard_deviation": (
                        standard_deviation
                    ),
                },
            )

        with self._lock:
            return float(
                self._generator.normal(
                    loc=mean,
                    scale=standard_deviation,
                )
            )

    def binomial(
        self,
        trials: int,
        probability: float,
    ) -> int:
        """
        Generate a binomially distributed count.
        """

        validated_trials = validate_integer(
            trials,
            field_name="trials",
            minimum=0,
        )

        validated_probability = (
            validate_probability(
                probability,
                field_name="probability",
            )
        )

        with self._lock:
            return int(
                self._generator.binomial(
                    validated_trials,
                    validated_probability,
                )
            )

    def sample_without_replacement(
        self,
        population_size: int,
        sample_size: int,
    ) -> list[int]:
        """
        Select unique integer indices without replacement.
        """

        validated_population = validate_integer(
            population_size,
            field_name="population_size",
            minimum=0,
        )

        validated_sample = validate_integer(
            sample_size,
            field_name="sample_size",
            minimum=0,
        )

        if validated_sample > validated_population:
            raise ProtocolValidationError(
                (
                    "Sample size cannot exceed "
                    "population size."
                ),
                details={
                    "population_size": (
                        validated_population
                    ),
                    "sample_size": validated_sample,
                },
            )

        if validated_sample == 0:
            return []

        with self._lock:
            selected = self._generator.choice(
                validated_population,
                size=validated_sample,
                replace=False,
            )

        return sorted(
            int(value)
            for value in selected.tolist()
        )

    def spawn(
        self,
        *components: object,
    ) -> "SimulationRandomManager":
        """
        Create an independent deterministic child generator.

        Example:

            channel_rng = manager.spawn(
                "urban",
                "partial_eve",
                session_id,
            )
        """

        child_seed = derive_deterministic_seed(
            *components,
            base_seed=self.seed,
        )

        return SimulationRandomManager(
            seed=child_seed
        )


# ---------------------------------------------------------------------
# Global simulation manager
# ---------------------------------------------------------------------

SIMULATION_RANDOM_MANAGER = (
    SimulationRandomManager(
        seed=RANDOM_SEED
    )
)


def get_simulation_rng() -> np.random.Generator:
    """
    Return the global NumPy simulation generator.
    """

    return (
        SIMULATION_RANDOM_MANAGER.generator
    )


def reset_simulation_rng(
    seed: int = RANDOM_SEED,
) -> None:
    """
    Reset the global simulation random manager.
    """

    SIMULATION_RANDOM_MANAGER.reset(seed)


def create_scenario_random_manager(
    scenario_name: str,
    session_id: str,
    *,
    base_seed: int = RANDOM_SEED,
) -> SimulationRandomManager:
    """
    Create a reproducible random manager for one demonstration scenario.

    Using the same scenario name, session ID, and base seed produces the
    same simulated noise and attack behaviour.
    """

    if not isinstance(
        scenario_name,
        str,
    ) or not scenario_name.strip():
        raise ConfigurationError(
            "Scenario name must be a non-empty string."
        )

    if not isinstance(
        session_id,
        str,
    ) or not session_id.strip():
        raise ConfigurationError(
            "Session ID must be a non-empty string."
        )

    scenario_seed = derive_deterministic_seed(
        scenario_name.strip().lower(),
        session_id.strip(),
        base_seed=base_seed,
    )

    return SimulationRandomManager(
        seed=scenario_seed
    )


__all__ = [
    "secure_random_bytes",
    "generate_nonce_bytes",
    "generate_nonce_hex",
    "generate_secure_token_hex",
    "generate_session_id",
    "secure_random_integer",
    "secure_random_bit",
    "secure_random_bits",
    "secure_shuffle",
    "derive_deterministic_seed",
    "SimulationRandomManager",
    "SIMULATION_RANDOM_MANAGER",
    "get_simulation_rng",
    "reset_simulation_rng",
    "create_scenario_random_manager",
]