"""
FT-QuPAP Gaussian Process Model Loader

This module loads and validates the trained FT-QuPAP Gaussian Process
attack-detection artifacts.

Supported artifact layouts
==========================

1. Final project structure:

    models/
        gp_model.pkl
        feature_scaler.pkl
        calibration_model.pkl
        threshold.json
        feature_order.json
        model_metadata.json

2. Notebook-compatible combined bundle:

    models/
        ft_qupap_gp_detector.joblib

Notebook bundle format:

    {
        "model": trained_gp_pipeline,
        "calibrator": optional_isotonic_calibrator,
        "feature_columns": FEATURE_COLUMNS,
        "protocol_version": "...",
        "seed": 20260701,
        "raw_calibration_gp_attack_threshold": 0.09,
        "gp_attack_threshold": 0.15,
        "training_source": "...",
        "calibration_method": "isotonic_regression",
        "session_gp_data_mode": "large",
        "session_gp_split_sizes": {...},
    }

Security warning
================

Joblib and pickle artifacts can execute Python code while loading.
Only load model artifacts generated by this trusted FT-QuPAP project.
Never load an untrusted model file received from another person or
downloaded from an unknown source.
"""

from __future__ import annotations

import copy
import json
import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import joblib
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from .feature_preprocessor import (
    load_feature_scaler,
    validate_scaler,
)
from .feature_schema import (
    FEATURE_COLUMNS,
    FEATURE_COUNT,
    validate_feature_order,
)


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MODEL_DIRECTORY = PROJECT_ROOT / "models"

DEFAULT_GP_MODEL_PATH = (
    DEFAULT_MODEL_DIRECTORY
    / "gp_model.pkl"
)

LEGACY_GP_BUNDLE_PATH = (
    DEFAULT_MODEL_DIRECTORY
    / "ft_qupap_gp_detector.joblib"
)

DEFAULT_FEATURE_SCALER_PATH = (
    DEFAULT_MODEL_DIRECTORY
    / "feature_scaler.pkl"
)

DEFAULT_CALIBRATION_MODEL_PATH = (
    DEFAULT_MODEL_DIRECTORY
    / "calibration_model.pkl"
)

DEFAULT_THRESHOLD_PATH = (
    DEFAULT_MODEL_DIRECTORY
    / "threshold.json"
)

DEFAULT_FEATURE_ORDER_PATH = (
    DEFAULT_MODEL_DIRECTORY
    / "feature_order.json"
)

DEFAULT_MODEL_METADATA_PATH = (
    DEFAULT_MODEL_DIRECTORY
    / "model_metadata.json"
)


MODEL_ARTIFACT_EXTENSIONS = frozenset(
    {
        ".pkl",
        ".joblib",
    }
)


class GPModelLoaderError(Exception):
    """Base exception for GP model-loading failures."""


class GPModelFileNotFoundError(
    GPModelLoaderError
):
    """Raised when no GP model artifact can be found."""


class InvalidGPModelArtifactError(
    GPModelLoaderError
):
    """Raised when a model artifact has an invalid format."""


class InvalidGPModelError(
    GPModelLoaderError
):
    """Raised when the loaded object is not a usable classifier."""


class InvalidGPCalibratorError(
    GPModelLoaderError
):
    """Raised when a calibration artifact is invalid."""


class GPFeatureSchemaMismatchError(
    GPModelLoaderError
):
    """Raised when the saved feature order differs from the schema."""


class InvalidGPThresholdError(
    GPModelLoaderError
):
    """Raised when threshold metadata is invalid."""


class InvalidGPMetadataError(
    GPModelLoaderError
):
    """Raised when model metadata is malformed."""


class ConflictingGPArtifactError(
    GPModelLoaderError
):
    """Raised when separate artifacts contain conflicting values."""


def validate_nonempty_string(
    value: Any,
    field_name: str,
    *,
    allow_none: bool = False,
) -> str | None:
    """Validate and normalize an optional or required string."""

    if value is None:
        if allow_none:
            return None

        raise TypeError(
            f"{field_name} cannot be None."
        )

    if not isinstance(
        value,
        str,
    ):
        raise TypeError(
            f"{field_name} must be a string."
        )

    normalized = value.strip()

    if not normalized:
        if allow_none:
            return None

        raise ValueError(
            f"{field_name} cannot be empty."
        )

    return normalized


def validate_optional_integer(
    value: Any,
    field_name: str,
) -> int | None:
    """Validate an optional integer metadata field."""

    if value is None:
        return None

    if (
        isinstance(value, bool)
        or not isinstance(value, int)
    ):
        raise TypeError(
            f"{field_name} must be an integer or None."
        )

    return value


def validate_probability(
    value: Any,
    field_name: str,
    *,
    allow_none: bool = False,
) -> float | None:
    """
    Validate a finite probability or threshold in [0, 1].
    """

    if value is None:
        if allow_none:
            return None

        raise InvalidGPThresholdError(
            f"{field_name} cannot be None."
        )

    if (
        isinstance(value, bool)
        or not isinstance(
            value,
            (int, float),
        )
    ):
        raise InvalidGPThresholdError(
            f"{field_name} must be numeric."
        )

    normalized = float(
        value
    )

    if not math.isfinite(
        normalized
    ):
        raise InvalidGPThresholdError(
            f"{field_name} must be finite."
        )

    if not 0.0 <= normalized <= 1.0:
        raise InvalidGPThresholdError(
            f"{field_name} must be between 0 and 1."
        )

    return normalized


def validate_artifact_path(
    path: str | Path,
    *,
    supported_extensions: frozenset[str] | None = None,
) -> Path:
    """Validate that an artifact path exists and is a file."""

    normalized_path = Path(
        path
    )

    if not normalized_path.exists():
        raise FileNotFoundError(
            f"Artifact does not exist: {normalized_path}"
        )

    if not normalized_path.is_file():
        raise InvalidGPModelArtifactError(
            f"Artifact path is not a file: {normalized_path}"
        )

    if supported_extensions is not None:
        if (
            normalized_path.suffix.lower()
            not in supported_extensions
        ):
            raise InvalidGPModelArtifactError(
                f"Unsupported artifact extension: "
                f"{normalized_path.suffix!r}"
            )

    return normalized_path


def load_trusted_joblib(
    path: str | Path,
) -> Any:
    """
    Load a trusted pickle/joblib artifact.

    Never call this function on an untrusted file.
    """

    normalized_path = validate_artifact_path(
        path,
        supported_extensions=(
            MODEL_ARTIFACT_EXTENSIONS
        ),
    )

    try:
        return joblib.load(
            normalized_path
        )

    except Exception as error:
        raise InvalidGPModelArtifactError(
            f"Could not load model artifact: "
            f"{normalized_path}"
        ) from error


def load_json_artifact(
    path: str | Path,
) -> Any:
    """Load one trusted JSON artifact."""

    normalized_path = validate_artifact_path(
        path
    )

    if normalized_path.suffix.lower() != ".json":
        raise InvalidGPModelArtifactError(
            "JSON artifact path must end with .json."
        )

    try:
        return json.loads(
            normalized_path.read_text(
                encoding="utf-8"
            )
        )

    except (
        OSError,
        UnicodeError,
        json.JSONDecodeError,
    ) as error:
        raise InvalidGPModelArtifactError(
            f"Could not read JSON artifact: "
            f"{normalized_path}"
        ) from error


def validate_gp_model(
    model: Any,
) -> Any:
    """
    Validate a probabilistic binary classification model.

    The model must expose predict_proba().
    """

    if model is None:
        raise InvalidGPModelError(
            "GP model cannot be None."
        )

    predict_proba = getattr(
        model,
        "predict_proba",
        None,
    )

    if not callable(
        predict_proba
    ):
        raise InvalidGPModelError(
            "GP model must provide predict_proba()."
        )

    classes = getattr(
        model,
        "classes_",
        None,
    )

    if classes is not None:
        try:
            normalized_classes = {
                int(value)
                for value in classes
            }

        except (
            TypeError,
            ValueError,
        ) as error:
            raise InvalidGPModelError(
                "Model classes_ could not be interpreted."
            ) from error

        if normalized_classes != {
            0,
            1,
        }:
            raise InvalidGPModelError(
                "FT-QuPAP GP model must use binary "
                "classes {0, 1}."
            )

    return model


def validate_calibrator(
    calibrator: Any,
) -> Any:
    """
    Validate a probability-calibration model.

    IsotonicRegression normally exposes predict(). Other supported
    calibrators may expose transform() or predict_proba().
    """

    if calibrator is None:
        raise InvalidGPCalibratorError(
            "Calibrator cannot be None."
        )

    supported_method_found = any(
        callable(
            getattr(
                calibrator,
                method_name,
                None,
            )
        )
        for method_name in (
            "predict",
            "transform",
            "predict_proba",
        )
    )

    if not supported_method_found:
        raise InvalidGPCalibratorError(
            "Calibration model must provide predict(), "
            "transform(), or predict_proba()."
        )

    return calibrator


def model_contains_scaler(
    model: Any,
) -> bool:
    """
    Return whether a loaded Pipeline already contains a scaler.

    This prevents the predictor from applying StandardScaler twice.
    """

    if not isinstance(
        model,
        Pipeline,
    ):
        return False

    for _, step in model.steps:
        if isinstance(
            step,
            StandardScaler,
        ):
            return True

    return False


def extract_feature_columns(
    artifact: Any,
) -> list[str]:
    """
    Extract feature order from supported JSON or bundle formats.
    """

    if isinstance(
        artifact,
        Mapping,
    ):
        for field_name in (
            "feature_columns",
            "feature_order",
            "features",
        ):
            if field_name in artifact:
                artifact = artifact[
                    field_name
                ]
                break

    if (
        isinstance(
            artifact,
            (str, bytes, bytearray),
        )
        or not isinstance(
            artifact,
            Sequence,
        )
    ):
        raise GPFeatureSchemaMismatchError(
            "Feature-order artifact must contain "
            "a sequence of feature names."
        )

    feature_columns = [
        str(column)
        for column in artifact
    ]

    try:
        validate_feature_order(
            feature_columns
        )

    except Exception as error:
        raise GPFeatureSchemaMismatchError(
            "GP feature schema mismatch."
        ) from error

    return feature_columns


def extract_threshold_values(
    artifact: Any,
) -> tuple[
    float | None,
    float | None,
]:
    """
    Extract operational and raw calibration thresholds.

    Supported JSON formats:

        0.15

        {
            "threshold": 0.15
        }

        {
            "gp_attack_threshold": 0.15,
            "raw_calibration_gp_attack_threshold": 0.09
        }
    """

    operational_threshold: Any = None
    raw_threshold: Any = None

    if isinstance(
        artifact,
        (int, float),
    ) and not isinstance(
        artifact,
        bool,
    ):
        operational_threshold = artifact

    elif isinstance(
        artifact,
        Mapping,
    ):
        for field_name in (
            "gp_attack_threshold",
            "selected_attack_threshold",
            "operational_threshold",
            "threshold",
        ):
            if field_name in artifact:
                operational_threshold = artifact[
                    field_name
                ]
                break

        for field_name in (
            "raw_calibration_gp_attack_threshold",
            "raw_calibration_threshold",
            "raw_threshold",
        ):
            if field_name in artifact:
                raw_threshold = artifact[
                    field_name
                ]
                break

    else:
        raise InvalidGPThresholdError(
            "Unsupported threshold artifact format."
        )

    return (
        validate_probability(
            operational_threshold,
            "gp_attack_threshold",
            allow_none=True,
        ),
        validate_probability(
            raw_threshold,
            "raw_calibration_gp_attack_threshold",
            allow_none=True,
        ),
    )


def merge_consistent_probability(
    first_value: float | None,
    second_value: float | None,
    field_name: str,
) -> float | None:
    """
    Merge two optional probability values and reject conflicts.
    """

    if first_value is None:
        return second_value

    if second_value is None:
        return first_value

    if not math.isclose(
        first_value,
        second_value,
        rel_tol=0.0,
        abs_tol=1e-12,
    ):
        raise ConflictingGPArtifactError(
            f"Conflicting {field_name} values: "
            f"{first_value} and {second_value}."
        )

    return first_value


def resolve_default_model_path(
    model_directory: str | Path = (
        DEFAULT_MODEL_DIRECTORY
    ),
) -> Path:
    """
    Resolve the preferred GP model artifact.

    Priority:

        1. models/gp_model.pkl
        2. models/ft_qupap_gp_detector.joblib
    """

    model_directory = Path(
        model_directory
    )

    candidates = (
        model_directory / "gp_model.pkl",
        model_directory
        / "ft_qupap_gp_detector.joblib",
    )

    for candidate in candidates:
        if candidate.is_file():
            return candidate

    raise GPModelFileNotFoundError(
        "No GP model artifact was found. Expected one of: "
        + ", ".join(
            str(candidate)
            for candidate in candidates
        )
    )


@dataclass
class GPModelBundle:
    """
    Validated FT-QuPAP GP model and associated artifacts.
    """

    model: Any

    feature_columns: tuple[str, ...] = tuple(
        FEATURE_COLUMNS
    )

    protocol_version: str | None = None
    seed: int | None = None

    calibrator: Any | None = None
    scaler: StandardScaler | None = None

    gp_attack_threshold: float | None = None

    raw_calibration_gp_attack_threshold: (
        float | None
    ) = None

    calibration_method: str | None = None
    training_source: str | None = None

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    source_paths: dict[str, str] = field(
        default_factory=dict
    )

    def __post_init__(self) -> None:
        self.model = validate_gp_model(
            self.model
        )

        try:
            validated_columns = (
                validate_feature_order(
                    self.feature_columns
                )
            )

        except Exception as error:
            raise GPFeatureSchemaMismatchError(
                "Loaded model feature order does not "
                "match FEATURE_COLUMNS."
            ) from error

        self.feature_columns = tuple(
            validated_columns
        )

        self.protocol_version = (
            validate_nonempty_string(
                self.protocol_version,
                "protocol_version",
                allow_none=True,
            )
        )

        self.seed = validate_optional_integer(
            self.seed,
            "seed",
        )

        if self.calibrator is not None:
            self.calibrator = (
                validate_calibrator(
                    self.calibrator
                )
            )

        if self.scaler is not None:
            self.scaler = validate_scaler(
                self.scaler,
                require_fitted=True,
            )

        self.gp_attack_threshold = (
            validate_probability(
                self.gp_attack_threshold,
                "gp_attack_threshold",
                allow_none=True,
            )
        )

        self.raw_calibration_gp_attack_threshold = (
            validate_probability(
                self.raw_calibration_gp_attack_threshold,
                (
                    "raw_calibration_"
                    "gp_attack_threshold"
                ),
                allow_none=True,
            )
        )

        self.calibration_method = (
            validate_nonempty_string(
                self.calibration_method,
                "calibration_method",
                allow_none=True,
            )
        )

        self.training_source = (
            validate_nonempty_string(
                self.training_source,
                "training_source",
                allow_none=True,
            )
        )

        if not isinstance(
            self.metadata,
            dict,
        ):
            raise InvalidGPMetadataError(
                "metadata must be a dictionary."
            )

        if not isinstance(
            self.source_paths,
            dict,
        ):
            raise InvalidGPMetadataError(
                "source_paths must be a dictionary."
            )

        self.metadata = copy.deepcopy(
            self.metadata
        )

        self.source_paths = {
            str(key): str(value)
            for key, value
            in self.source_paths.items()
        }

        if (
            self.model_contains_scaler
            and self.scaler is not None
        ):
            self.metadata[
                "external_scaler_redundant"
            ] = True

    @property
    def feature_count(self) -> int:
        """Return the expected GP input width."""

        return len(
            self.feature_columns
        )

    @property
    def calibrated(self) -> bool:
        """Return whether a probability calibrator is loaded."""

        return self.calibrator is not None

    @property
    def threshold_available(self) -> bool:
        """Return whether an operational threshold was loaded."""

        return (
            self.gp_attack_threshold
            is not None
        )

    @property
    def model_contains_scaler(self) -> bool:
        """Return whether the model Pipeline scales internally."""

        return model_contains_scaler(
            self.model
        )

    @property
    def external_scaler_required(self) -> bool:
        """
        Return whether prediction requires the external scaler.
        """

        return bool(
            self.scaler is not None
            and not self.model_contains_scaler
        )

    def notebook_bundle(
        self,
    ) -> dict[str, Any]:
        """
        Return a notebook-compatible GP bundle dictionary.
        """

        bundle: dict[str, Any] = {
            "model":
                self.model,
            "feature_columns":
                list(
                    self.feature_columns
                ),
            "protocol_version":
                self.protocol_version,
            "seed":
                self.seed,
        }

        if self.calibrator is not None:
            bundle[
                "calibrator"
            ] = self.calibrator

        if self.scaler is not None:
            bundle[
                "scaler"
            ] = self.scaler

        if self.gp_attack_threshold is not None:
            bundle[
                "gp_attack_threshold"
            ] = self.gp_attack_threshold

        if (
            self.raw_calibration_gp_attack_threshold
            is not None
        ):
            bundle[
                "raw_calibration_gp_attack_threshold"
            ] = (
                self.raw_calibration_gp_attack_threshold
            )

        if self.calibration_method is not None:
            bundle[
                "calibration_method"
            ] = self.calibration_method

        if self.training_source is not None:
            bundle[
                "training_source"
            ] = self.training_source

        bundle.update(
            copy.deepcopy(
                self.metadata
            )
        )

        return bundle

    def describe(
        self,
    ) -> dict[str, Any]:
        """
        Return JSON-safe model information without estimator objects.
        """

        return {
            "model_type":
                type(self.model).__name__,

            "feature_columns":
                list(
                    self.feature_columns
                ),

            "feature_count":
                self.feature_count,

            "protocol_version":
                self.protocol_version,

            "seed":
                self.seed,

            "calibrated":
                self.calibrated,

            "calibrator_type": (
                None
                if self.calibrator is None
                else type(
                    self.calibrator
                ).__name__
            ),

            "model_contains_scaler":
                self.model_contains_scaler,

            "external_scaler_loaded":
                self.scaler is not None,

            "external_scaler_required":
                self.external_scaler_required,

            "gp_attack_threshold":
                self.gp_attack_threshold,

            "raw_calibration_gp_attack_threshold":
                self.raw_calibration_gp_attack_threshold,

            "calibration_method":
                self.calibration_method,

            "training_source":
                self.training_source,

            "source_paths":
                dict(
                    self.source_paths
                ),

            "metadata":
                copy.deepcopy(
                    self.metadata
                ),
        }


def load_gp_model_bundle(
    model_path: str | Path | None = None,
    *,
    model_directory: str | Path = (
        DEFAULT_MODEL_DIRECTORY
    ),
    scaler_path: str | Path | None = None,
    calibrator_path: str | Path | None = None,
    threshold_path: str | Path | None = None,
    feature_order_path: str | Path | None = None,
    metadata_path: str | Path | None = None,
    require_calibrator: bool = False,
    require_threshold: bool = False,
    load_redundant_scaler: bool = False,
) -> GPModelBundle:
    """
    Load and validate all FT-QuPAP GP artifacts.

    The function automatically supports both the notebook bundle and
    the separate-artifact project structure.
    """

    model_directory = Path(
        model_directory
    )

    if model_path is None:
        resolved_model_path = (
            resolve_default_model_path(
                model_directory
            )
        )

    else:
        resolved_model_path = (
            validate_artifact_path(
                model_path,
                supported_extensions=(
                    MODEL_ARTIFACT_EXTENSIONS
                ),
            )
        )

    loaded_model_artifact = (
        load_trusted_joblib(
            resolved_model_path
        )
    )

    combined_bundle: dict[str, Any]

    if isinstance(
        loaded_model_artifact,
        Mapping,
    ) and "model" in loaded_model_artifact:
        combined_bundle = dict(
            loaded_model_artifact
        )

        model = combined_bundle[
            "model"
        ]

    else:
        combined_bundle = {}
        model = loaded_model_artifact

    model = validate_gp_model(
        model
    )

    source_paths: dict[str, str] = {
        "model":
            str(
                resolved_model_path.resolve()
            )
    }

    bundle_feature_columns: list[str] | None = None

    if "feature_columns" in combined_bundle:
        bundle_feature_columns = (
            extract_feature_columns(
                combined_bundle[
                    "feature_columns"
                ]
            )
        )

    if feature_order_path is None:
        possible_feature_path = (
            model_directory
            / "feature_order.json"
        )

        if possible_feature_path.is_file():
            feature_order_path = (
                possible_feature_path
            )

    external_feature_columns: list[str] | None = None

    if feature_order_path is not None:
        feature_order_artifact = (
            load_json_artifact(
                feature_order_path
            )
        )

        external_feature_columns = (
            extract_feature_columns(
                feature_order_artifact
            )
        )

        source_paths[
            "feature_order"
        ] = str(
            Path(
                feature_order_path
            ).resolve()
        )

    if (
        bundle_feature_columns is not None
        and external_feature_columns is not None
        and bundle_feature_columns
        != external_feature_columns
    ):
        raise ConflictingGPArtifactError(
            "Combined bundle and feature_order.json "
            "contain different feature orders."
        )

    selected_feature_columns = (
        external_feature_columns
        or bundle_feature_columns
        or list(FEATURE_COLUMNS)
    )

    try:
        validate_feature_order(
            selected_feature_columns
        )

    except Exception as error:
        raise GPFeatureSchemaMismatchError(
            "Loaded GP feature order does not "
            "match the current schema."
        ) from error

    calibrator = combined_bundle.get(
        "calibrator"
    )

    if calibrator_path is None:
        possible_calibrator_path = (
            model_directory
            / "calibration_model.pkl"
        )

        if possible_calibrator_path.is_file():
            calibrator_path = (
                possible_calibrator_path
            )

    if (
        calibrator is None
        and calibrator_path is not None
    ):
        calibrator = load_trusted_joblib(
            calibrator_path
        )

        source_paths[
            "calibrator"
        ] = str(
            Path(
                calibrator_path
            ).resolve()
        )

    if calibrator is not None:
        calibrator = validate_calibrator(
            calibrator
        )

    if require_calibrator and calibrator is None:
        raise InvalidGPCalibratorError(
            "A calibrated model bundle is required, "
            "but no calibrator was found."
        )

    scaler = combined_bundle.get(
        "scaler"
    )

    internal_scaler = model_contains_scaler(
        model
    )

    if scaler_path is None:
        possible_scaler_path = (
            model_directory
            / "feature_scaler.pkl"
        )

        if possible_scaler_path.is_file():
            scaler_path = (
                possible_scaler_path
            )

    if (
        scaler is None
        and scaler_path is not None
        and (
            not internal_scaler
            or load_redundant_scaler
        )
    ):
        scaler = load_feature_scaler(
            scaler_path
        )

        source_paths[
            "scaler"
        ] = str(
            Path(
                scaler_path
            ).resolve()
        )

    if scaler is not None:
        scaler = validate_scaler(
            scaler,
            require_fitted=True,
        )

    bundle_operational_threshold = (
        validate_probability(
            combined_bundle.get(
                "gp_attack_threshold"
            ),
            "gp_attack_threshold",
            allow_none=True,
        )
    )

    bundle_raw_threshold = (
        validate_probability(
            combined_bundle.get(
                "raw_calibration_gp_attack_threshold"
            ),
            (
                "raw_calibration_"
                "gp_attack_threshold"
            ),
            allow_none=True,
        )
    )

    if threshold_path is None:
        possible_threshold_path = (
            model_directory
            / "threshold.json"
        )

        if possible_threshold_path.is_file():
            threshold_path = (
                possible_threshold_path
            )

    external_operational_threshold: float | None = None
    external_raw_threshold: float | None = None

    if threshold_path is not None:
        threshold_artifact = (
            load_json_artifact(
                threshold_path
            )
        )

        (
            external_operational_threshold,
            external_raw_threshold,
        ) = extract_threshold_values(
            threshold_artifact
        )

        source_paths[
            "threshold"
        ] = str(
            Path(
                threshold_path
            ).resolve()
        )

    operational_threshold = (
        merge_consistent_probability(
            bundle_operational_threshold,
            external_operational_threshold,
            "gp_attack_threshold",
        )
    )

    raw_threshold = (
        merge_consistent_probability(
            bundle_raw_threshold,
            external_raw_threshold,
            (
                "raw_calibration_"
                "gp_attack_threshold"
            ),
        )
    )

    if (
        require_threshold
        and operational_threshold is None
    ):
        raise InvalidGPThresholdError(
            "An operational GP threshold is required, "
            "but no threshold artifact was found."
        )

    external_metadata: dict[str, Any] = {}

    if metadata_path is None:
        possible_metadata_path = (
            model_directory
            / "model_metadata.json"
        )

        if possible_metadata_path.is_file():
            metadata_path = (
                possible_metadata_path
            )

    if metadata_path is not None:
        loaded_metadata = load_json_artifact(
            metadata_path
        )

        if not isinstance(
            loaded_metadata,
            Mapping,
        ):
            raise InvalidGPMetadataError(
                "model_metadata.json must contain "
                "a JSON object."
            )

        external_metadata = dict(
            loaded_metadata
        )

        source_paths[
            "metadata"
        ] = str(
            Path(
                metadata_path
            ).resolve()
        )

    protocol_version = (
        external_metadata.get(
            "protocol_version",
            combined_bundle.get(
                "protocol_version"
            ),
        )
    )

    seed = external_metadata.get(
        "seed",
        combined_bundle.get(
            "seed"
        ),
    )

    calibration_method = (
        external_metadata.get(
            "calibration_method",
            combined_bundle.get(
                "calibration_method"
            ),
        )
    )

    training_source = (
        external_metadata.get(
            "training_source",
            combined_bundle.get(
                "training_source"
            ),
        )
    )

    excluded_bundle_keys = {
        "model",
        "calibrator",
        "scaler",
        "feature_columns",
        "protocol_version",
        "seed",
        "gp_attack_threshold",
        "raw_calibration_gp_attack_threshold",
        "calibration_method",
        "training_source",
    }

    metadata = {
        key: copy.deepcopy(
            value
        )
        for key, value
        in combined_bundle.items()
        if key not in excluded_bundle_keys
    }

    metadata.update(
        copy.deepcopy(
            external_metadata
        )
    )

    return GPModelBundle(
        model=model,
        feature_columns=tuple(
            selected_feature_columns
        ),
        protocol_version=protocol_version,
        seed=seed,
        calibrator=calibrator,
        scaler=scaler,
        gp_attack_threshold=(
            operational_threshold
        ),
        raw_calibration_gp_attack_threshold=(
            raw_threshold
        ),
        calibration_method=(
            calibration_method
        ),
        training_source=training_source,
        metadata=metadata,
        source_paths=source_paths,
    )


def load_gp_bundle(
    path: str | Path | None = None,
    *,
    model_directory: str | Path = (
        DEFAULT_MODEL_DIRECTORY
    ),
) -> dict[str, Any]:
    """
    Notebook-compatible model-loading function.

    The original notebook performs:

        bundle = joblib.load(path)

        if bundle["feature_columns"] != FEATURE_COLUMNS:
            raise ValueError("GP feature schema mismatch.")

    This project implementation performs additional artifact and
    estimator validation before returning the same dictionary format.
    """

    loaded_bundle = load_gp_model_bundle(
        model_path=path,
        model_directory=model_directory,
    )

    return loaded_bundle.notebook_bundle()


class GPModelLoader:
    """
    Reusable FT-QuPAP GP artifact loader with optional caching.
    """

    def __init__(
        self,
        model_directory: str | Path = (
            DEFAULT_MODEL_DIRECTORY
        ),
        *,
        require_calibrator: bool = False,
        require_threshold: bool = False,
    ) -> None:
        self.model_directory = Path(
            model_directory
        )

        self.require_calibrator = bool(
            require_calibrator
        )

        self.require_threshold = bool(
            require_threshold
        )

        self._cached_bundle: (
            GPModelBundle | None
        ) = None

    @property
    def loaded(self) -> bool:
        """Return whether a bundle is cached."""

        return self._cached_bundle is not None

    def clear_cache(self) -> None:
        """Remove the cached model bundle."""

        self._cached_bundle = None

    def load(
        self,
        *,
        force_reload: bool = False,
    ) -> GPModelBundle:
        """
        Load or return the cached validated GP model bundle.
        """

        if (
            self._cached_bundle is not None
            and not force_reload
        ):
            return self._cached_bundle

        self._cached_bundle = (
            load_gp_model_bundle(
                model_directory=(
                    self.model_directory
                ),
                require_calibrator=(
                    self.require_calibrator
                ),
                require_threshold=(
                    self.require_threshold
                ),
            )
        )

        return self._cached_bundle

    def load_notebook_bundle(
        self,
        *,
        force_reload: bool = False,
    ) -> dict[str, Any]:
        """Return the loaded bundle as a notebook dictionary."""

        return self.load(
            force_reload=force_reload
        ).notebook_bundle()

    def describe(
        self,
        *,
        force_reload: bool = False,
    ) -> dict[str, Any]:
        """Return non-estimator model information."""

        return self.load(
            force_reload=force_reload
        ).describe()


def run_self_test() -> None:
    """
    Verify separate-artifact and notebook-bundle loading.
    """

    import tempfile

    import numpy as np
    from sklearn.isotonic import (
        IsotonicRegression,
    )
    from sklearn.linear_model import (
        LogisticRegression,
    )

    with tempfile.TemporaryDirectory() as temporary:
        model_directory = Path(
            temporary
        )

        training_features = np.asarray(
            [
                [
                    0.00,
                    0.00,
                    0.0,
                    0.00,
                    0.00,
                    0.00,
                    1.0,
                    0.0,
                    0.0,
                ],
                [
                    0.02,
                    0.20,
                    1.0,
                    0.00,
                    0.01,
                    0.01,
                    0.0,
                    1.0,
                    0.0,
                ],
                [
                    0.04,
                    0.40,
                    1.0,
                    0.01,
                    0.02,
                    0.02,
                    0.0,
                    0.0,
                    1.0,
                ],
                [
                    0.20,
                    2.00,
                    4.0,
                    0.20,
                    0.05,
                    0.10,
                    1.0,
                    0.0,
                    0.0,
                ],
                [
                    0.30,
                    3.00,
                    5.0,
                    0.30,
                    0.08,
                    0.15,
                    0.0,
                    1.0,
                    0.0,
                ],
                [
                    0.40,
                    4.00,
                    6.0,
                    0.40,
                    0.10,
                    0.20,
                    0.0,
                    0.0,
                    1.0,
                ],
            ],
            dtype=float,
        )

        labels = np.asarray(
            [
                0,
                0,
                0,
                1,
                1,
                1,
            ],
            dtype=int,
        )

        model = Pipeline(
            steps=[
                (
                    "scaler",
                    StandardScaler(),
                ),
                (
                    "classifier",
                    LogisticRegression(
                        random_state=7,
                        max_iter=200,
                    ),
                ),
            ]
        )

        model.fit(
            training_features,
            labels,
        )

        calibrator = IsotonicRegression(
            out_of_bounds="clip"
        )

        calibrator.fit(
            np.asarray(
                [
                    0.0,
                    0.25,
                    0.50,
                    0.75,
                    1.0,
                ]
            ),
            np.asarray(
                [
                    0.0,
                    0.10,
                    0.50,
                    0.90,
                    1.0,
                ]
            ),
        )

        joblib.dump(
            model,
            model_directory
            / "gp_model.pkl",
        )

        joblib.dump(
            calibrator,
            model_directory
            / "calibration_model.pkl",
        )

        (
            model_directory
            / "feature_order.json"
        ).write_text(
            json.dumps(
                {
                    "feature_columns":
                        FEATURE_COLUMNS,
                }
            ),
            encoding="utf-8",
        )

        (
            model_directory
            / "threshold.json"
        ).write_text(
            json.dumps(
                {
                    "raw_calibration_gp_attack_threshold":
                        0.09,

                    "gp_attack_threshold":
                        0.15,
                }
            ),
            encoding="utf-8",
        )

        (
            model_directory
            / "model_metadata.json"
        ).write_text(
            json.dumps(
                {
                    "protocol_version":
                        "FT-QuPAP-test",

                    "seed":
                        20260701,

                    "training_source":
                        "self_test",

                    "calibration_method":
                        "isotonic_regression",
                }
            ),
            encoding="utf-8",
        )

        loader = GPModelLoader(
            model_directory,
            require_calibrator=True,
            require_threshold=True,
        )

        separate_bundle = loader.load()

        if (
            separate_bundle.feature_count
            != FEATURE_COUNT
        ):
            raise GPModelLoaderError(
                "Feature count is incorrect."
            )

        if (
            separate_bundle.gp_attack_threshold
            != 0.15
        ):
            raise GPModelLoaderError(
                "Operational threshold was not loaded."
            )

        if (
            separate_bundle
            .raw_calibration_gp_attack_threshold
            != 0.09
        ):
            raise GPModelLoaderError(
                "Raw threshold was not loaded."
            )

        if not separate_bundle.calibrated:
            raise GPModelLoaderError(
                "Calibration model was not loaded."
            )

        if not (
            separate_bundle.model_contains_scaler
        ):
            raise GPModelLoaderError(
                "Internal model scaler was not detected."
            )

        combined_path = (
            model_directory
            / "combined_bundle.joblib"
        )

        joblib.dump(
            {
                "model":
                    model,

                "calibrator":
                    calibrator,

                "feature_columns":
                    FEATURE_COLUMNS,

                "protocol_version":
                    "FT-QuPAP-test-combined",

                "seed":
                    20260701,

                "raw_calibration_gp_attack_threshold":
                    0.09,

                "gp_attack_threshold":
                    0.15,

                "training_source":
                    "combined_self_test",

                "calibration_method":
                    "isotonic_regression",
            },
            combined_path,
        )

        combined_bundle = (
            load_gp_model_bundle(
                model_path=combined_path,
                model_directory=(
                    model_directory
                ),
                feature_order_path=(
                    model_directory
                    / "feature_order.json"
                ),
                threshold_path=(
                    model_directory
                    / "threshold.json"
                ),
            )
        )

        if (
            combined_bundle.protocol_version
            != "FT-QuPAP-test"
        ):
            # Separate model_metadata.json is treated as the
            # project-level authoritative metadata artifact.
            raise GPModelLoaderError(
                "Project metadata priority is incorrect."
            )

        notebook_bundle = (
            combined_bundle.notebook_bundle()
        )

        if (
            notebook_bundle[
                "feature_columns"
            ]
            != FEATURE_COLUMNS
        ):
            raise GPModelLoaderError(
                "Notebook feature order is incorrect."
            )

        if not callable(
            notebook_bundle[
                "model"
            ].predict_proba
        ):
            raise GPModelLoaderError(
                "Loaded model is unusable."
            )

        print(
            "GP model loader self-test "
            "completed successfully."
        )

        print(
            "Feature count:",
            separate_bundle.feature_count,
        )

        print(
            "Protocol version:",
            separate_bundle.protocol_version,
        )

        print(
            "Calibrator loaded:",
            separate_bundle.calibrated,
        )

        print(
            "Model contains scaler:",
            separate_bundle.model_contains_scaler,
        )

        print(
            "Operational threshold:",
            separate_bundle.gp_attack_threshold,
        )


__all__ = [
    "PROJECT_ROOT",
    "DEFAULT_MODEL_DIRECTORY",
    "DEFAULT_GP_MODEL_PATH",
    "LEGACY_GP_BUNDLE_PATH",
    "DEFAULT_FEATURE_SCALER_PATH",
    "DEFAULT_CALIBRATION_MODEL_PATH",
    "DEFAULT_THRESHOLD_PATH",
    "DEFAULT_FEATURE_ORDER_PATH",
    "DEFAULT_MODEL_METADATA_PATH",
    "MODEL_ARTIFACT_EXTENSIONS",
    "GPModelLoaderError",
    "GPModelFileNotFoundError",
    "InvalidGPModelArtifactError",
    "InvalidGPModelError",
    "InvalidGPCalibratorError",
    "GPFeatureSchemaMismatchError",
    "InvalidGPThresholdError",
    "InvalidGPMetadataError",
    "ConflictingGPArtifactError",
    "GPModelBundle",
    "GPModelLoader",
    "validate_nonempty_string",
    "validate_optional_integer",
    "validate_probability",
    "validate_artifact_path",
    "load_trusted_joblib",
    "load_json_artifact",
    "validate_gp_model",
    "validate_calibrator",
    "model_contains_scaler",
    "extract_feature_columns",
    "extract_threshold_values",
    "merge_consistent_probability",
    "resolve_default_model_path",
    "load_gp_model_bundle",
    "load_gp_bundle",
]


if __name__ == "__main__":
    try:
        run_self_test()

    except (
        GPModelLoaderError,
        TypeError,
        ValueError,
        OSError,
    ) as error:
        print(
            "\n[GP MODEL LOADER ERROR] "
            f"{error}"
        )

        raise SystemExit(1) from error